### ISSUE TITLE
AttributeError: 'Unicode' object has no attribute 'tag' in Python2

### ISSUE THREAD

**Issue by sara-02** [mwaskom/seaborn#1011]
I have both Python 2.7.12 and Python 3.5.1 on Fedora24, I did dnf install for python2-seaborn and Python3-seaborn.
Importing seaborn is Python3 is working fine, but in Python2 I get the following error.
```
import seaborn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/seaborn/__init__.py", line 11, in <module>
    from .widgets import *
  File "/usr/lib/python2.7/site-packages/seaborn/widgets.py", line 8, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/usr/lib/python2.7/site-packages/ipywidgets/__init__.py", line 22, in <module>
    from .widgets import *
  File "/usr/lib/python2.7/site-packages/ipywidgets/widgets/__init__.py", line 1, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization, handle_version_comm_opened
  File "/usr/lib/python2.7/site-packages/ipywidgets/widgets/widget.py", line 117, in <module>
    class Widget(LoggingConfigurable):
  File "/usr/lib/python2.7/site-packages/ipywidgets/widgets/widget.py", line 154, in Widget
    in which to find _model_name. If empty, look in the global registry.""").tag(sync=True)
AttributeError: 'Unicode' object has no attribute 'tag'
```

**Comment by mwaskom** [comment]
Can you import `ipywidgets` directly? That's where the error is getting raised from.

**Comment by hainm** [comment]
@sara-02 `pip install traitlets --upgrade` should help.

https://github.com/ipython/traitlets/issues/48

**Comment by sara-02** [comment]
@mwaskom It worked after importing ipwidgets.

**Comment by fortyMiles** [comment]
@hainm Thanks!
