### ISSUE TITLE
"make test" failed with OSError 

### ISSUE THREAD

**Issue by tetsu911** [mwaskom/seaborn#1082]
Hi all,

"make test" met OSError in my computer. Could you please tell me how to fix it?
My environment is;
OS Ubuntu1604
Python 2.7.12

Thank you,

```
$$ make test
cp testing/matplotlibrc .
nosetests --with-doctest
E
======================================================================
ERROR: Failure: OSError (/usr/local/lib/python2.7/dist-packages/zmq/libzmq_d.so: undefined symbol: Py_InitModule4TraceRefs_64)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/t080070/gits/seaborn/seaborn/__init__.py", line 16, in <module>
    from .widgets import *
  File "/home/t080070/gits/seaborn/seaborn/widgets.py", line 8, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/usr/local/lib/python2.7/dist-packages/ipywidgets/__init__.py", line 22, in <module>
    from .widgets import *
  File "/usr/local/lib/python2.7/dist-packages/ipywidgets/widgets/__init__.py", line 1, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization, handle_version_comm_opened
  File "/usr/local/lib/python2.7/dist-packages/ipywidgets/widgets/widget.py", line 14, in <module>
    from ipykernel.comm import Comm
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/usr/local/lib/python2.7/dist-packages/zmq/__init__.py", line 39, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python2.7/dist-packages/zmq/libzmq_d.so: undefined symbol: Py_InitModule4TraceRefs_64

----------------------------------------------------------------------
Ran 1 test in 0.944s

FAILED (errors=1)
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by tetsu911** [comment]
I'm sorry for disturbing you.
Updating Cython and PyZMQ fixes this problem, so I close this issue.
