### ISSUE TITLE
axisgrid fails with matplotlib v2

### ISSUE THREAD

**Issue by dstansby** [mwaskom/seaborn#1094]
Trying to plot a `joinplot`, and axisgrid is failing with:

```
Traceback (most recent call last):
  File "jet_statistics.py", line 114, in <module>
    xlim=lims, ylim=lims)
  File "/home/dstansby/seaborn/seaborn/distributions.py", line 798, in jointplot
    xlim=xlim, ylim=ylim)
  File "/home/dstansby/seaborn/seaborn/axisgrid.py", line 1643, in __init__
    plt.setp(ax_marg_x.yaxis.get_minorticklines(), visible=False)
  File "/home/dstansby/miniconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 359, in setp
    return _setp(*args, **kwargs)
  File "/home/dstansby/miniconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 1430, in setp
    insp = ArtistInspector(objs[0])
IndexError: list index out of range
```

I think this is because `ax_marg_x.yaxis.get_minorticklines()` is a list of zero length, which in matplotlib 2 causes `plt.setp` to throw an `IndexError`.

**Comment by mwaskom** [comment]
Please post a reproducible example of code that causes the problem.

**Comment by dstansby** [comment]
Bizarrely I can't reproduce this any more. I'll reopen with an example if it appears again.

**Comment by drammock** [comment]
I can reproduce this with:

```python
import numpy as np
import seaborn as sns
x = np.random.randn(10)
y = np.random.randn(10)
g = sns.jointplot(x, y, kind='kde')
```
```
Traceback (most recent call last):
  File "/home/drmccloy/Desktop/mwe.py", line 16, in <module>
    g = sns.jointplot(x, y, kind='kde')
  File "/home/drmccloy/Builds/seaborn/seaborn/distributions.py", line 798, in jointplot
    xlim=xlim, ylim=ylim)
  File "/home/drmccloy/Builds/seaborn/seaborn/axisgrid.py", line 1642, in __init__
    plt.setp(ax_marg_x.yaxis.get_minorticklines(), visible=False)
  File "/home/drmccloy/.local/lib/python2.7/site-packages/matplotlib-1.5.1+1643.g0423430-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 350, in setp
    return _setp(*args, **kwargs)
  File "/home/drmccloy/.local/lib/python2.7/site-packages/matplotlib-1.5.1+1643.g0423430-py2.7-linux-x86_64.egg/matplotlib/artist.py", line 1555, in setp
    insp = ArtistInspector(objs[0])
IndexError: list index out of range
```
Here are my versions:

```
sns.__version__
# '0.8.dev'
np.__version__
# '1.12.0.dev0+2af06c8'
import matplotlib as mpl
mpl.__version__
# '1.5.1+1643.g0423430'
```

**Comment by drammock** [comment]
I should add that I'm getting this on latest master (just pulled down 993c6a2 today, and ran `python setup.py develop` before running this MWE)

**Comment by mwaskom** [comment]
Your code runs fine for me on current seaborn master and matplotlib 2.0.0. It looks like you're using an old development version of matplotlib — maybe this was something they fixed?

**Comment by drammock** [comment]
Hmm, updating and recompiling matplotlib will have to wait a few days; I'll try to remember to check back in once I do that.

**Comment by drammock** [comment]
confirmed that this works after updating matplotlib. thanks @mwaskom.

**Comment by laurensvdwiel** [comment]
The proposed fix in this issue also worked for me for matplotlib v1.4.3
