### ISSUE TITLE
import  seaborn error

### ISSUE THREAD

**Issue by Ke-1** [mwaskom/seaborn#1172]
```Traceback (most recent call last):
  File "/Users/one/coone_analysis/Python/pyfile/test.py", line 3, in <module>
    import seaborn as sns
  File "/usr/local/lib/python3.6/site-packages/seaborn/__init__.py", line 16, in <module>
    from .widgets import *
  File "/usr/local/lib/python3.6/site-packages/seaborn/widgets.py", line 8, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "/usr/local/lib/python3.6/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/usr/local/lib/python3.6/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization, handle_version_comm_opened
  File "/usr/local/lib/python3.6/site-packages/ipywidgets/widgets/widget.py", line 13, in <module>
    from ipykernel.comm import Comm
  File "/usr/local/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.6/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/__init__.py", line 8, in <module>
    from .blocking import BlockingKernelClient
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/__init__.py", line 1, in <module>
    from .client import BlockingKernelClient
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/client.py", line 72, in <module>
    class BlockingKernelClient(KernelClient):
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/client.py", line 152, in BlockingKernelClient
    execute = reqrep(KernelClient.execute)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/client.py", line 49, in reqrep
    basedoc, _ = meth.__doc__.split('Returns\n', 1)
AttributeError: 'NoneType' object has no attribute 'split'
[Finished in 1.8s]

**Comment by mwaskom** [comment]
If you read the traceback, which contains some very valuable information, ot looks like you have some problem with your `ipywidgets` installation.

**Comment by Ke-1** [comment]
I tried reinstall this two package. However, it still does't work. But when I user shell or  jupyter notebook it works. So I think maybe there are some problem with my sublime build python

**Comment by mwaskom** [comment]
Sounds like it's not a problem in seaborn but you're on the right path to tracking it down.
