### ISSUE TITLE
import seaborn error: underlying buffer has been detached

### ISSUE THREAD

**Issue by Jethi** [mwaskom/seaborn#1200]
Hi,
In my local machine seaborn is working fine with flask. But when I try to host the flask application in IIS, I am getting this error:
" underlying buffer has been detached"
Please help me with this issue.

**Comment by mwaskom** [comment]
I'm sorry but it is impossible for me to help you with only this amount of information.

**Comment by Jethi** [comment]
Hi @mwaskom ,
I tried to put the import statement in try-except block and log the exception caused is being written to the log file. I am only getting the error "underlying buffer has been detached". The import of seaborn works fine in local machine, but on IIS server I am getting this error. Could you please help me this? 
try:
    import seaborn as sns
    with open("D:/logs.txt","a") as f:
        f.write("200")
except Exception as e:
    with open("D:/logs.txt","a") as f:
        f.write("error"+str(e))

**Comment by Jethi** [comment]
Hi @mwaskom ,

I tried to log the traceback error caused due to importing seaborn. Results are below. Any help regarding this? 

Traceback (most recent call last):
  File ".\toolAPIs\pptGenerator_API.py", line 62, in <module>
    import seaborn as sns
  File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\__init__.py", line 16, in <module>
    from .widgets import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\seaborn\widgets.py", line 8, in <module>
    from ipywidgets import interact, FloatSlider, IntSlider
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipywidgets\__init__.py", line 23, in <module>
    from IPython import get_ipython
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 17, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 62, in <module>
    from IPython.utils import io
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 97, in <module>
    stdin = IOStream(sys.stdin, fallback=devnull)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 41, in __init__
    for meth in filter(clone, dir(stream)):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 40, in clone
    return not hasattr(self, meth) and not meth.startswith('_')
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\utils\io.py", line 84, in closed
    return self.stream.closed
ValueError: underlying buffer has been detached

**Comment by mwaskom** [comment]
I have no idea what IIS is.

**Comment by Jethi** [comment]
IIS is nothing but a Microsoft server we are using for hosting our web application. Any idea why is this error occuring ?

**Comment by mwaskom** [comment]
No, sorry.
