### ISSUE TITLE
jointplot: specific keyerror error should be raised when passing data and column is missing

### ISSUE THREAD

**Issue by Prikers** [mwaskom/seaborn#1204]
I think a specific `KeyError ` should be raised when data is provided and either `x` or `y` is a string but not a valid key of the DataFrame. 

This code:
```python
import pandas as pd
import numpy as np
import searbon as sns

df = pd.DataFrame(columns = list('ABCD'),
                  data = np.random.rand(100, 4))

sns.jointplot(x='A', y='NOT_A_VALID_COLUMN', data=df)
```
returns the following error:
```python
Traceback (most recent call last):

  File "<ipython-input-20-0d129181776f>", line 1, in <module>
    sns.jointplot(x='A', y='NOT_A_VALID_COLUMN', data=df)

  File "C:\Users\...\Anaconda3\lib\site-packages\seaborn\distributions.py", line 798, in jointplot
    xlim=xlim, ylim=ylim)

  File "C:\Users\...\Anaconda3\lib\site-packages\seaborn\axisgrid.py", line 1661, in __init__
    y = y[not_na]

TypeError: string indices must be integers
```
A `KeyError` would be less confusing when debugging. And the figure could be not created.

**Comment by mwaskom** [comment]
Yes, the cost of input flexibility is that it's harder to do input validation ...

**Comment by Prikers** [comment]
I will propose a pull request then. Thanks!

**Comment by Prikers** [comment]
#1211 added
