### ISSUE TITLE
Runtime error on Mac OSX virtualenv

### ISSUE THREAD

**Issue by mikkokotila** [mwaskom/seaborn#1253]
I'm getting the following: 

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1j/zwfrrpdn273280_kyjhkmkdh0000gn/T/pip-nsX5XM-build/setup.py", line 93, in <module>
        install_requires = check_dependencies()
      File "/private/var/folders/1j/zwfrrpdn273280_kyjhkmkdh0000gn/T/pip-nsX5XM-build/setup.py", line 85, in check_dependencies
        import seaborn
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/seaborn/__init__.py", line 6, in <module>
        from .rcmod import *
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/seaborn/rcmod.py", line 8, in <module>
        from . import palettes, _orig_rc_params
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/seaborn/palettes.py", line 12, in <module>
        from .utils import desaturate, set_hls_values, get_color_cycle
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/seaborn/utils.py", line 12, in <module>
        import matplotlib.pyplot as plt
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
        globals(),locals(),[backend_name],0)
      File "/Users/mikko/dev/new_test/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
        from matplotlib.backends import _macosx
    RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```
This yields as a result of having seaborn as one of the dependencies in setup.py. It seems that when Seaborn is installed, it checks which system is in question and if Mac OSX is in question, then tries to import that backend. This is what yields the error. I found that if instead use use() and for example TKagg, then this error is avoided. Any recommendations for how to best handle this?

**Comment by mwaskom** [comment]
The behavior you're describing is all done by matplotlib, not seaborn. But it sounds like you have found a way to avoid the problem by specifying the matplotlib backend to use.
