### ISSUE TITLE
Invalid RGBA argument, when creating pointplot

### ISSUE THREAD

**Issue by bobekhj** [mwaskom/seaborn#1263]
## Problem:
I use python 2.7 and I want to draw a pointplot. However, I get an error in the matplotlib colors.py file. It looks like seaborn is passing a float value to matlib and it doesn't like that. I updated both the matplotlib and seaborn to newest versions using pip.

## Sample code:
```
import seaborn as sns

grid = sns.FacetGrid(train_df, col='Survived', row='Embarked')
grid.map(sns.pointplot, 'Pclass', 'Survived', 'Sex')
grid.add_legend()

```
## Stack trace: 

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    grid.map(sns.pointplot, 'Pclass', 'Survived', 'Sex')
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/seaborn/axisgrid.py", line 731, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/seaborn/axisgrid.py", line 815, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/seaborn/categorical.py", line 3129, in pointplot
    plotter.plot(ax)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/seaborn/categorical.py", line 1780, in plot
    self.draw_points(ax)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/seaborn/categorical.py", line 1776, in draw_points
    edgecolor=self.colors[j], zorder=z)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/__init__.py", line 1898, in inner
    return func(ax, *args, **kwargs)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4034, in scatter
    alpha=alpha
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/collections.py", line 902, in __init__
    Collection.__init__(self, **kwargs)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/collections.py", line 141, in __init__
    self.set_edgecolor(edgecolors)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/collections.py", line 741, in set_edgecolor
    self._set_edgecolor(c)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/collections.py", line 722, in _set_edgecolor
    self._edgecolors = mcolors.to_rgba_array(c, self._alpha)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/colors.py", line 239, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/colors.py", line 143, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/Users/hubertjarema/Virtualenvs/titanic-ml/lib/python2.7/site-packages/matplotlib/colors.py", line 194, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 0.12156862745098039
```

**Comment by mwaskom** [comment]
This looks like yet another instance of matplotlib's irritating behavior of interpreting an RGB tuple as a scalar array when three values are passed into `scatter`.

**Comment by bobekhj** [comment]
@mwaskom Hi, Thanks for your quick reply. Is there a fix, or workaround for this problem? Thank you

**Comment by mwaskom** [comment]
Not a great one but this works:

```
import seaborn as sns
train_df = sns.load_dataset("titanic")
grid = sns.FacetGrid(train_df, col='survived', row='embarked')
grid.map(sns.pointplot, 'pclass', 'survived', 'sex', order=[1, 2, 3, 4])
grid.set(xlim=(-.5, 2.5))
```

**Comment by mwaskom** [comment]
ps unrelated to this issue but in general you should use `sns.factorplot` instead of `sns.FacetGrid + `sns.pointplot` as the former handles some important bookkeeping related to standardizing categorical axes across the facets.
