### ISSUE TITLE
seaborn import issue with pandas 0.21, scipy 1.0

### ISSUE THREAD

**Issue by apiszcz** [mwaskom/seaborn#1315]
```
Traceback (most recent call last):
  File "lib\_test\test.py", line 99, in <module>
    import seaborn as sns; sns.set()
  File "C:\g\app\lib\seaborn\__init__.py", line 6, in <module>
    from .rcmod import *
  File "C:\g\app\lib\seaborn\rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "C:\g\app\lib\seaborn\palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "C:\g\app\lib\seaborn\utils.py", line 7, in <module>
    from scipy import stats
  File "C:\g\app\lib\scipy\__init__.py", line 118, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\g\app\lib\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c'
```

**Comment by mwaskom** [comment]
What's your evidence that this is a seaborn issue? The import error is coming from scipy.

**Comment by apiszcz** [comment]
Agree will post there, the import started in seaborn.
