### ISSUE TITLE
pairplot: long column names raise ValueError('Width and height specified must be non-negative') 

### ISSUE THREAD

**Issue by pirius** [mwaskom/seaborn#1375]
Hi Michael,

with `pairplot()` long column names seem to cause a `ValueError('Width and height specified must be non-negative')`. This might also effect other plots but I had no time to check details yet. Consider this example:

```python
import pandas as pd
import seaborn as sns; sns.set(style="ticks", color_codes=True)

sns_data = pd.DataFrame({'a': [0,1,2,3], 'b': [0,1,4,8]})
pd.plotting.scatter_matrix(sns_data) # for comparison, works fine
sns.pairplot(sns_data) # works fine

sns_data = pd.DataFrame({
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa': [0,1,2,3], 
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb': [0,1,4,8]})
pd.plotting.scatter_matrix(sns_data) # for comparison, looks ugly but works fine
sns.pairplot(sns_data) # raises error
```
The full error is:

```
sns.pairplot(sns_data)
Traceback (most recent call last):

  File "<ipython-input-228-be97c446266e>", line 1, in <module>
    sns.pairplot(sns_data)

  File "/opt/anaconda/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2060, in pairplot
    grid.map_diag(plt.hist, **diag_kws)

  File "/opt/anaconda/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1337, in map_diag
    diag_ax = ax._make_twin_axes(sharex=ax, frameon=False)

  File "/opt/anaconda/lib/python3.6/site-packages/matplotlib/axes/_subplots.py", line 158, in _make_twin_axes
    *kl, **kwargs)

  File "/opt/anaconda/lib/python3.6/site-packages/matplotlib/axes/_subplots.py", line 73, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)

  File "/opt/anaconda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 488, in __init__
    raise ValueError('Width and height specified must be non-negative')

ValueError: Width and height specified must be non-negative
```
Used versions:

```
sns.__version__
'0.8.1'
pd.__version__
'0.22.0'
```
Best regards

**Comment by mwaskom** [comment]
The error is getting raised from matplotlib. What would you like me to do about it?

**Comment by pirius** [comment]
Afaiu this is caused by seaborn deriving certain plot parameters from the data, which are then handed to matplotlib but are invalid given their API specification. Correct me if I'm wrong about this. My guess would be that seaborn users would expect `sns.pairplot()` to work also when using long column names, similarly to what `pd.plotting.scatter_matrix()` does in the example above. Otherwise they would have to additionally adapt column names before being able to use it.

**Comment by mwaskom** [comment]
I don't know. I really don't have time to look into it right now, sorry.
