### ISSUE TITLE
Can't import seaborn

### ISSUE THREAD

**Issue by sunworshipper** [mwaskom/seaborn#1388]
I wasn't able to find anything with this kind of error so here it goes.

Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

Scipy 1
Numpy 1.13.3
Pandas 0.22

```
>>> import matplotlib
>>> import seaborn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.6/site-packages/seaborn/__init__.py", line 9, in <module>
    from .regression import *
  File "//anaconda/lib/python3.6/site-packages/seaborn/regression.py", line 27, in <module>
    from .axisgrid import FacetGrid, _facet_docs
  File "//anaconda/lib/python3.6/site-packages/seaborn/axisgrid.py", line 16, in <module>
    from .distributions import distplot, kdeplot,  _freedman_diaconis_bins
  File "//anaconda/lib/python3.6/site-packages/seaborn/distributions.py", line 13, in <module>
    import statsmodels.nonparametric.api as smnp
  File "//anaconda/lib/python3.6/site-packages/statsmodels/nonparametric/api.py", line 1, in <module>
    from .kde import KDEUnivariate
  File "//anaconda/lib/python3.6/site-packages/statsmodels/nonparametric/kde.py", line 22, in <module>
    from statsmodels.tools.decorators import (cache_readonly,
  File "//anaconda/lib/python3.6/site-packages/statsmodels/tools/decorators.py", line 199, in <module>
    from nose.tools import nottest
  File "/usr/local/Cellar/numpy/1.12.0/libexec/nose/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/local/Cellar/numpy/1.12.0/libexec/nose/lib/python2.7/site-packages/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
                        ^
SyntaxError: invalid syntax
```

**Comment by mwaskom** [comment]
It looks like somehow your packages in a python 3 anaconda environment end up trying to import dependencies from a python 2 macports envirnonment. The specific error is the difference between python 2 and 3 print syntax. The broader error is that something has gone quite wrong with your python setup. (Maybe your $PYTHONPATH?) In any case it’s not a seaborn issue.

**Comment by sunworshipper** [comment]
Thank you that pointed me in the right direction.  I had a conflict with brew installed numpy from a previous opencv install.
