### ISSUE TITLE
Using set with color_palette() output fails

### ISSUE THREAD

**Issue by vinay-jayaram** [mwaskom/seaborn#1546]
When creating a color palette using the color_palette() function, an error is thrown in 0.9.0 when trying to pass the output to sns.set(). MWE:

```
import seaborn as sns

pal = sns.color_palette("husl")
sns.set(palette=pal)
```

This appears to be for all named palettes

**Comment by mwaskom** [comment]
What is the error

**Comment by vinay-jayaram** [comment]
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/is/ei/vjayaram/anaconda/envs/moabb_p3/lib/python3.6/site-packages/seaborn/rcmod.py", line 121, in set
    set_palette(palette, color_codes=color_codes)
  File "/is/ei/vjayaram/anaconda/envs/moabb_p3/lib/python3.6/site-packages/seaborn/rcmod.py", line 549, in set_palette
    palettes.set_color_codes(palette)
  File "/is/ei/vjayaram/anaconda/envs/moabb_p3/lib/python3.6/site-packages/seaborn/palettes.py", line 1070, in set_color_codes
    elif palette in SEABORN_PALETTES:
TypeError: unhashable type: '_ColorPalette'

**Comment by mwaskom** [comment]
I think that's a bug. Can be worked around right now but adding `color_codes=False`.
