### ISSUE TITLE
sizes parameter for scatterplot does not accept dict with more than 2 objets

### ISSUE THREAD

**Issue by lejocelyn** [mwaskom/seaborn#1570]
When trying to build a scatterplot with my data, I'd like to pass a dictionary to the sizes parameter, so
that I can have the same legend from one graphic to another.
If I write : 
```
ax = sns.scatterplot(x="pourcents", y="sources",
                                hue="textua_simplifié", size="NOM", palette=couleur, hue_order=["introduction",                                    "péripétie", "chant", "conclusion","autre","dialogue"],
                                sizes={0:20,1:250},
                                data=vieux)
plt.show()
```

I have the following error message : 
`ValueError: Missing sizes for the following levels: {2, 4, 5}`
Which is normal. But if I write instead : 
```
ax = sns.scatterplot(x="pourcents", y="sources",
                                hue="textua_simplifié", size="NOM", palette=couleur, hue_order=["introduction",                                    "péripétie", "chant", "conclusion","autre","dialogue"],
                                sizes={0:20,1:100,2:150,4:200,5:250},
                                data=vieux)
plt.show()
```
I get the following error:
[...]
``` /usr/local/lib/python3.6/site-packages/seaborn/relational.py in size_lookup(self, key)
    281         if self.size_type == "numeric":
    282             min_size, max_size = self.size_range
 --> 283             val = self.size_norm(key)
    284             if np.ma.is_masked(val):
    285                 return 0
TypeError: 'NoneType' object is not callable
```

I'm quite new to Seaborn, but it seems to me that it is not the intended behaviour.

**Comment by MaozGelbart** [comment]
Hi @lejocelyn , could you add a reproducible example?

**Comment by MaozGelbart** [comment]
I reduced this issue to a reproducible example of what seems to be a bug (although, the bug description is different than current title):
```python
import seaborn as sns

x=y=[1]
s=[0]
ax=sns.scatterplot(x=x,y=y,size=s, sizes={0:200})
```
That produces the following error:
```python
Traceback (most recent call last):
  File "D:\1570.py", line 5, in <module>
    ax=sns.scatterplot(x=x,y=y,size=s, sizes={0:200})
  File "C:\ProgramData\Miniconda3\lib\site-packages\seaborn\relational.py", line 1341, in scatterplot
    p.plot(ax, kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\seaborn\relational.py", line 929, in plot
    self.add_legend_data(ax)
  File "C:\ProgramData\Miniconda3\lib\site-packages\seaborn\relational.py", line 609, in add_legend_data
    size = self.size_lookup(level)
  File "C:\ProgramData\Miniconda3\lib\site-packages\seaborn\relational.py", line 283, in size_lookup
    val = self.size_norm(key)
TypeError: 'NoneType' object is not callable
```
The code plots well when not providing the ``sizes`` argument, or when ``legend=False``, or when the size datatype is not numeric. It seems that when ``sizes`` is a valid ``dict``, the legend numeric size mapping is still looking for the level size using the ``size_norm`` which was not set and therefore it fails.
