### ISSUE TITLE
clustermap cannot handle matrix more than 8,000 by 8,000

### ISSUE THREAD

**Issue by deniseduma** [mwaskom/seaborn#1581]
Hi,

I'm using clustermap to plot a heat map of my genes, the correlation matrix that I would like to use as input to clustermap is around 15,000 by 15,000. However, it seems that clustermap is unable to handle any matrix larger than 8,000 by 8,000 which is pretty disappointing! 

Here is the error message I get when calling clustermap:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2787, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  [Previous line repeated 993 more times]
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2754, in _dendrogram_calculate_info
    above_threshold_color=above_threshold_color)
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2666, in _dendrogram_calculate_info
    leaf_label_func, i, labels)
  File "/usr/local/lib/python3.6/dist-packages/scipy/cluster/hierarchy.py", line 2539, in _append_singleton_leaf_node
    ivl.append(str(int(i)))
RecursionError: maximum recursion depth exceeded while getting the str of an object

I understand the error is probably caused by the underlying scipy.cluster.hierarchy package that clustermap is calling under the hood, but is there any way I could somehow use clustermap to plot the heatmap of my genes? A matrix more than 8,000 by 8,000 is hardly unusual in computational biology and if Python cannot handle these kind of dimensions than it seems to be a very serious drawback!

Looking  forward to your reply.

Regards,
Denise

**Comment by mwaskom** [comment]
The error is not raised from seaborn, so I can’t help you, sorry.
