### ISSUE TITLE
Error when plotting bars with error bars

### ISSUE THREAD

**Issue by pletzer** [mwaskom/seaborn#1672]
Hi,

I've not been able to error bars in barplot for data that have two categories, called 'type' and 'results' below. 

The following code generates an error:

import pandas as pd
import seaborn as sns

t = [['a', 'better', 0.7, 0.1], ['a', 'same', 0.3, 0.01], ['a', 'worse', 0., 0.], ['b', 'better', 0.1, 0.05], ['b', 'same', 0.6, 0.1], ['b', 'worse', 0.3, 0.1]]
df = pd.DataFrame(data=t, columns=['type', 'result', 'proportion', 'error'])
sns.barplot(data=df, x='result', y='proportion', hue='type', yerr=df['error'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py", line 3154, in barplot
    plotter.plot(ax, kwargs)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py", line 1661, in plot
    self.draw_bars(ax, bar_kws)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/seaborn/categorical.py", line 1646, in draw_bars
    label=hue_level, **kws)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 2312, in bar
    fmt='none', **error_kw)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 3319, in errorbar
    lower, upper = extract_err(yerr, y)
  File "/Users/pletzera/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 3260, in extract_err
    raise ValueError("err must be [ scalar | N, Nx1 "
ValueError: err must be [ scalar | N, Nx1 or 2xN array-like ]

**Comment by pletzer** [comment]
The same error occurs with 

sns.barplot(data=df, x='result', y='proportion', yerr=df['error'])

**Comment by pletzer** [comment]
sns.__version__
'0.9.0'

**Comment by pletzer** [comment]
It works with a fix error bar:
sns.barplot(data=df, x='result', y='proportion', yerr=0.1)
<matplotlib.axes._subplots.AxesSubplot object at 0x1a179821d0>

**Comment by pletzer** [comment]
It works when working with one type:

dfa = df[df['type'] == 'a']
sns.barplot(data=dfa, x='result', y='proportion', yerr=dfa['error'])
<matplotlib.axes._subplots.AxesSubplot object at 0x1a179821d0>

**Comment by pletzer** [comment]
This issue appears to be similar to 

https://stackoverflow.com/questions/42017049/seaborn-how-to-add-error-bars-on-a-grouped-barplot

**Comment by mwaskom** [comment]
This is all expected behavior. `yerr` is a keyword parameter in the underlying matlab function, not part of the seaborn API.
