### ISSUE TITLE
Catplot error with hue parameter and matplotlib 3.0.2

### ISSUE THREAD

**Issue by kaisengit** [mwaskom/seaborn#1697]
I am reporting an error here which appeared after updating matploblib from 2.1.2 to 3.0.2. You can use the code I posted in this issue to reproduce (but I think just plotting any kind of catplot with the hue parameter causes it): #1696 

Make sure you are using the following line for plotting:
```
fg = sns.catplot(data=df, x='id', y='val', hue='exp', col='exp', kind='point',col_wrap=3, ci='sd', sharey=False, sharex=False)
```

The following error is thrown:
```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4238, in scatter
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./seaborn_map_bug.py", line 54, in <module>
    fg = sns.catplot(data=df, x='id', y='val', hue='exp', col='exp', kind='point',col_wrap=3, ci='sd', sharey=False, sharex=False)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/categorical.py", line 3755, in catplot
    g.map_dataframe(plot_func, x, y, hue, **plot_kws)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 820, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 838, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/categorical.py", line 3340, in pointplot
    plotter.plot(ax)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/categorical.py", line 1811, in plot
    self.draw_points(ax)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/seaborn/categorical.py", line 1807, in draw_points
    zorder=z)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/opt/miniconda3/envs/plot/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4245, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 4 elements, which is not acceptable for use with 'x' with size 0, 'y' with size 0.
```

It can be 'fixed' by replacing these lines in matploblib: https://github.com/matplotlib/matplotlib/blob/003cd72ec2bb01ebc1162988dbe441df25d1f591/lib/matplotlib/axes/_axes.py#L4230-L4256

With the corresponding ones from matploblib 2.x:
https://github.com/matplotlib/matplotlib/blob/00ee41b9f3abc94ecb44d7f572339f4a8559338e/lib/matplotlib/axes/_axes.py#L4285-L4295

Note that the error only appears with the hue parameter. Maybe it is related to my other issue: #1696 

It seems to be caused by a 'fix' in matploblib: https://github.com/matplotlib/matplotlib/issues/10365

The following package versions were used:
```
matplotlib                3.0.2            py37h5429711_0  
numpy                     1.16.2           py37h7e9f1db_0  
numpy-base                1.16.2           py37hde5b4d6_0  
pandas                    0.24.1           py37he6710b0_0  
seaborn                   0.9.0                    py37_0 
```

**Comment by mwaskom** [comment]
Yes unfortunately a "helpful fix" in matplotlib broke seaborn. This is tracked elsewhere, thanks.
