### ISSUE TITLE
pandas 0.25.2 seems to affect seaborn

### ISSUE THREAD

**Issue by manmartgarc** [mwaskom/seaborn#1858]
It seems that the newest version of pandas breaks `statsmodels` which in turns breaks `seaborn`?

```
import seaborn as sns
Traceback (most recent call last):

  File "<ipython-input-121-a84c0541e888>", line 1, in <module>
    import seaborn as sns

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\seaborn\__init__.py", line 9, in <module>
    from .relational import *

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\seaborn\relational.py", line 18, in <module>
    from .axisgrid import FacetGrid, _facet_docs

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\seaborn\axisgrid.py", line 16, in <module>
    from .distributions import distplot, kdeplot,  _freedman_diaconis_bins

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\seaborn\distributions.py", line 16, in <module>
    import statsmodels.nonparametric.api as smnp

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\nonparametric\__init__.py", line 7, in <module>
    from statsmodels.tools._testing import PytestTester

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\__init__.py", line 1, in <module>
    from .tools import add_constant, categorical

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\tools.py", line 9, in <module>
    from statsmodels.compat.python import (reduce, lzip, lmap, asstr2, range,

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\compat\__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester

  File "C:\Users\mmarti10\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tools\_testing.py", line 19, in <module>
    import pandas.util.testing as tm

AttributeError: module 'pandas.util' has no attribute 'testing'
```

**Comment by manmartgarc** [comment]
It was an issue with my own venv
