### ISSUE TITLE
[BUG] mask usage breaks with v0.10.1

### ISSUE THREAD

**Issue by slumnitz** [mwaskom/seaborn#2153]
Hello seaborn team, 

this code snippet worked with seaborn 0.10.0 and broke with 0.10.1.
We depend on it working in our package: https://github.com/pysal/splot 

Please let us know if this can be fixed, or if best practices for mask generations hanged. Thank you!

```
import numpy as np
import seaborn as sns

heatmap_data = np.array([[31,  0,  0,  0,  1],
       [ 3,  5,  0,  0,  0],
       [ 0,  0,  1,  0,  0],
       [ 2,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0]])

diagonal_mask = np.array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

sns.heatmap(heatmap_data, mask=diagonal_mask)
```

Gives the following error:
```
Traceback (most recent call last):
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 473, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bug_report.py", line 16, in <module>
    sns.heatmap(heatmap_data, mask=diagonal_mask)
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/seaborn/matrix.py", line 537, in heatmap
    yticklabels, mask)
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/seaborn/matrix.py", line 165, in __init__
    cmap, center, robust)
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/seaborn/matrix.py", line 198, in _determine_cmap_params
    calc_data = plot_data.filled(np.nan)
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 3739, in filled
    fill_value = _check_fill_value(fill_value, self.dtype)
  File "/Users/steffie/miniconda3/envs/dev/lib/python3.7/site-packages/numpy/ma/core.py", line 479, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Cannot convert fill_value nan to dtype int64
```

**Comment by mwaskom** [comment]
I believe this has a fix in https://github.com/mwaskom/seaborn/pull/2103

And indeed, I cannot replicate the issue on master.

**Comment by mwaskom** [comment]
Current workaround would be to cast the input data to float.
