### ISSUE TITLE
Known matplotlib issue with tight_layout, "RuntimeError: CGContextRef is NULL", on the first tutorial example

### ISSUE THREAD

**Issue by jona-sassenhagen** [mwaskom/seaborn#231]
When running the tutorial on Mac OS X, the very first example won't work (see copy paste below).

It's a known issue in matplotlib:
https://github.com/matplotlib/matplotlib/issues/2654
Is it possible to either fix it, or at least warn Mac users about it? Might lose some potential customers otherwise.
It works when using another backend.

Code:

```
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pandas as pd
>>> import seaborn as sns
>>> import matplotlib as mpl
>>> import matplotlib.pyplot as plt
>>> np.random.seed(sum(map(ord, "linear_quantitative")))
>>> tips = sns.load_dataset("tips")
>>> sns.lmplot("total_bill", "tip", tips);
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/seaborn/linearmodels.py", line 724, in lmplot
    legend=legend, legend_out=legend_out)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/seaborn/axisgrid.py", line 215, in __init__
    fig.tight_layout()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/figure.py", line 1606, in tight_layout
    rect=rect)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/tight_layout.py", line 352, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/tight_layout.py", line 129, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/tight_layout.py", line 129, in <listcomp>
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes.py", line 9161, in get_tightbbox
    bb_xaxis = self.xaxis.get_tightbbox(renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 1060, in get_tightbbox
    renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 1043, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/text.py", line 755, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/text.py", line 321, in _get_layout
    ismath=False)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/backends/backend_macosx.py", line 158, in get_text_width_height_descent
    width, height, descent = self.gc.get_text_width_height_descent(str(s), family, size, weight, style)
RuntimeError: CGContextRef is NULL
>>> 
```

**Comment by csaid** [comment]
While we wait for this matplotlib issue to get fixed, are either of you aware of a workaround?

I am unable to run this:
```
g = sns.FacetGrid(df, col='agentName', col_wrap=4, size=2)
```

Because of this error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-1927ff991430> in <module>()
     20 # f.tight_layout()
     21 # plt.gcf().set_tight_layout(True)
---> 22 g = sns.FacetGrid(df, col='agentName', col_wrap=4, size=2)

/opt/twitter/lib/python2.7/site-packages/seaborn/axisgrid.pyc in __init__(self, data, row, col, hue, col_wrap, sharex, sharey, size, aspect, palette, row_order, col_order, hue_order, hue_kws, dropna, legend_out, despine, margin_titles, xlim, ylim, subplot_kws)
    341
    342         # Make the axes look good
--> 343         fig.tight_layout()
    344         if despine:
    345             self.despine()

/opt/twitter/lib/python2.7/site-packages/matplotlib/figure.pyc in tight_layout(self, renderer, pad, h_pad, w_pad, rect)
   1652                                          renderer,
   1653                                          pad=pad, h_pad=h_pad, w_pad=w_pad,
-> 1654                                          rect=rect)
   1655
   1656         self.subplots_adjust(**kwargs)

/opt/twitter/lib/python2.7/site-packages/matplotlib/tight_layout.pyc in get_tight_layout_figure(fig, axes_list, subplotspec_list, renderer, pad, h_pad, w_pad, rect)
    350                                      subplot_list=subplot_list,
    351                                      ax_bbox_list=ax_bbox_list,
--> 352                                      pad=pad, h_pad=h_pad, w_pad=w_pad)
    353
    354     if rect is not None:

/opt/twitter/lib/python2.7/site-packages/matplotlib/tight_layout.pyc in auto_adjust_subplotpars(fig, renderer, nrows_ncols, num1num2_list, subplot_list, ax_bbox_list, pad, h_pad, w_pad, rect)
    127         #ax_bbox = union([ax.get_position(original=True) for ax in subplots])
    128
--> 129         tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots])
    130         tight_bbox = TransformedBbox(tight_bbox_raw,
    131                                      fig.transFigure.inverted())

/opt/twitter/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in get_tightbbox(self, renderer, call_axes_locator)
   3260             bb.append(bb_xaxis)
   3261
-> 3262         bb_yaxis = self.yaxis.get_tightbbox(renderer)
   3263         if bb_yaxis:
   3264             bb.append(bb_yaxis)

/opt/twitter/lib/python2.7/site-packages/matplotlib/axis.pyc in get_tightbbox(self, renderer)
   1080         ticks_to_draw = self._update_ticks(renderer)
   1081         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
-> 1082                                                                 renderer)
   1083
   1084         self._update_label_position(ticklabelBoxes, ticklabelBoxes2)

/opt/twitter/lib/python2.7/site-packages/matplotlib/axis.pyc in _get_tick_bboxes(self, ticks, renderer)
   1063         for tick in ticks:
   1064             if tick.label1On and tick.label1.get_visible():
-> 1065                 extent = tick.label1.get_window_extent(renderer)
   1066                 ticklabelBoxes.append(extent)
   1067             if tick.label2On and tick.label2.get_visible():

/opt/twitter/lib/python2.7/site-packages/matplotlib/text.pyc in get_window_extent(self, renderer, dpi)
    739             raise RuntimeError('Cannot get window extent w/o renderer')
    740
--> 741         bbox, info, descent = self._get_layout(self._renderer)
    742         x, y = self.get_position()
    743         x, y = self.get_transform().transform_point((x, y))

/opt/twitter/lib/python2.7/site-packages/matplotlib/text.pyc in _get_layout(self, renderer)
    309         tmp, lp_h, lp_bl = renderer.get_text_width_height_descent('lp',
    310                                                          self._fontproperties,
--> 311                                                          ismath=False)
    312         offsety = (lp_h - lp_bl) * self._linespacing
    313

/opt/twitter/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.pyc in get_text_width_height_descent(self, s, prop, ismath)
    164         size = self.points_to_pixels(points)
    165         width, height, descent = self.gc.get_text_width_height_descent(
--> 166             six.text_type(s), family, size, weight, style)
    167         return  width, height, 0.0*descent
    168

RuntimeError: CGContextRef is NULL
```
I'm on OSX using the latest version of matplotlib (1.4.2) and seaborn (0.5.1)

**Comment by csaid** [comment]
OK cool thanks. Just in case others come across this thread with the same problem, here is what I got to work: 

```
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import seaborn as sns
```

A lot of the other backends didn't work or had dependencies that couldn't be easily installed on my machine.

**Comment by mwaskom** [comment]
just out of curiosity why aren't you using the notebook?

**Comment by mwaskom** [comment]
Ah, well, embrace change my friend :)

Anyway in case people end up here on google, I should say that the interactive stuff is the hard part and if you're just writing a script that you're executing non-interactively you can use the `Agg` backend which I believe will work out of the box on any basic matplotlib installation.

**Comment by GregSilverman** [comment]
Same issue using iPython in the console of PyCharm. It is a problem, and it still has not been fixed.
