### ISSUE TITLE
Heatmap fails with Matplotlib pgf backend

### ISSUE THREAD

**Issue by tlaundal** [mwaskom/seaborn#2343]
Due to matplotlib/matplotlib#18407, uses of `seaborn.heatmap` errors out with `AttributeError: 'NoneType' object has no attribute 'write'` when using the pgf backend for Matplotlib.

## Minimal reproducible example
```py
import matplotlib
import seaborn

matplotlib.use('pgf')
seaborn.heatmap([[1, 2], [3, 4]])
```

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    seaborn.heatmap([[1, 2], [3, 4]])
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/seaborn/matrix.py", line 558, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/seaborn/matrix.py", line 342, in plot
    ax.figure.draw(ax.figure.canvas.get_renderer())
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/figure.py", line 1862, in draw
    self.patch.draw(renderer)
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/patches.py", line 587, in draw
    draw_path(tpath, affine,
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/backends/backend_pgf.py", line 475, in draw_path
    writeln(self.fh, r"\begin{pgfscope}")
  File "/home/tlaundal/Projects/seaborn-pgf-bug/env/lib/python3.8/site-packages/matplotlib/backends/backend_pgf.py", line 129, in writeln
    fh.write(line)
AttributeError: 'NoneType' object has no attribute 'write'
```

## Possible solution
Besides waiting for Matplotlib to fix this, which it seems they will, a quick fix is to change how the draw is triggered in [`matrix.py` line 342](https://github.com/mwaskom/seaborn/blob/v0.11.0/seaborn/matrix.py#L342) as [suggested](https://github.com/matplotlib/matplotlib/issues/18407#issuecomment-687223797) in the upstream issue.
```diff
diff --git a/seaborn/matrix.py b/seaborn/matrix.py
index 60c19cf..f6d413e 100644
--- a/seaborn/matrix.py
+++ b/seaborn/matrix.py
@@ -339,7 +339,8 @@ class _HeatMapper(object):

         # Possibly rotate them if they overlap
         if hasattr(ax.figure.canvas, "get_renderer"):
-            ax.figure.draw(ax.figure.canvas.get_renderer())
+            ax.figure.canvas.draw()
         if axis_ticklabels_overlap(xtl):
             plt.setp(xtl, rotation="vertical")
         if axis_ticklabels_overlap(ytl):
```
~~I'll create a PR with this change as well.~~
I have verified that this fix works in my specific case. I have seen the same line repeated elsewhere in `matrix.py`, but I have not researched if it is used in other modules or what the side effects of changing it are.

**Comment by mwaskom** [comment]
Reopening; see #2408

**Comment by mwaskom** [comment]
Note that the change suggested here is only a partial fix in that `fig.canvas.draw` is actually a no-op on the pgf backend. That's a matplotlib bug that seaborn can't do anything about.  On some other backends (notably the osx backend) that's also a no-op, but the fact that the figure is not actually drawn breaks seaborn in other places. Hence #2426.
