### ISSUE TITLE
kdeplot takes the wrong column

### ISSUE THREAD

**Issue by MiqG** [mwaskom/seaborn#2345]
Hi, 

I got this weird error lately that I don't know how to solve when using `sns.kdeplot()`. I seems like it tries to plot a different column than indicated from the dataframe.

Error example:
```shell
pc:~$ conda list | grep 'pandas\|seaborn'
biopandas                 0.2.5              pyh9f0ad1d_0    conda-forge
pandas                    1.1.1            py38he6710b0_0  
seaborn                   0.10.0                     py_0
(base) :~$ python
Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn as sns
>>> import matplotlib.pyplot as plt
>>> geyser = sns.load_dataset("geyser")
>>> sns.kdeplot(data=geyser, x="waiting", y="duration")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.8/site-packages/seaborn/distributions.py", line 667, in kdeplot
    data = data.astype(np.float64)
  File "/opt/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5537, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "/opt/miniconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 595, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/opt/miniconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 406, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/miniconda3/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 589, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/opt/miniconda3/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 989, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'long'
```

Then, when subsetting the dataframe to only those two columns, I get this other error:
```shell
>>> sns.kdeplot(data=geyser[['waiting','duration']], x="waiting", y="duration")
/opt/miniconda3/lib/python3.8/site-packages/seaborn/distributions.py:693: UserWarning: Passing a 2D dataset for a bivariate plot is deprecated in favor of kdeplot(x, y), and it will cause an error in future versions. Please update your code.
  warnings.warn(warn_msg, UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.8/site-packages/seaborn/distributions.py", line 699, in kdeplot
    ax = _bivariate_kdeplot(x, y, shade, shade_lowest,
TypeError: _bivariate_kdeplot() got multiple values for argument 'x'
```

However, this works:
```shell
>>> sns.kdeplot(geyser[['waiting','duration']]);plt.show()
```

Thanks!

**Comment by mwaskom** [comment]
`kdeplot` did not support a `data=, x=, y=` signature until [0.11.0](http://seaborn.pydata.org/whatsnew.html#changes-to-existing-functions).
