### ISSUE TITLE
Pairplot function return AttributeError with combination of diag_kind=None and corner=True

### ISSUE THREAD

**Issue by GentilsTo** [mwaskom/seaborn#2354]
As stated in the title, it seems like there is an issue when trying to use a combination of diag_kind=None and corner=True in the pairplot function. This raise an AttributeError exception.

```Python
import seaborn as sns

iris = sns.load_dataset('iris')
sns.pairplot(iris , diag_kind=None, corner=True)
```

which return:
```Python
Traceback (most recent call last):

  File "<ipython-input-87-23324450a106>", line 1, in <module>
    sns.pairplot(p, diag_kind=None, corner=True)

  File "c:\program files\python38\lib\site-packages\seaborn\_decorators.py", line 46, in inner_f
    return f(**kwargs)

  File "c:\program files\python38\lib\site-packages\seaborn\axisgrid.py", line 1974, in pairplot
    plotter(scatterplot, **plot_kws)

  File "c:\program files\python38\lib\site-packages\seaborn\axisgrid.py", line 1250, in map
    self._map_bivariate(func, indices, **kwargs)

  File "c:\program files\python38\lib\site-packages\seaborn\axisgrid.py", line 1434, in _map_bivariate
    self._plot_bivariate(x_var, y_var, ax, func, **kws)

  File "c:\program files\python38\lib\site-packages\seaborn\axisgrid.py", line 1446, in _plot_bivariate
    plt.sca(ax)

  File "C:\Users\tgentils\AppData\Roaming\Python\Python38\site-packages\matplotlib\pyplot.py", line 982, in sca
    if not hasattr(ax.figure.canvas, "manager"):

AttributeError: 'NoneType' object has no attribute 'figure'
```

**Comment by mwaskom** [comment]
Thank you for the reproducible example. For completeness, can you please provide the versions of seaborn and matplotlib that you  are using.

**Comment by GentilsTo** [comment]
So, I get this with the following setup:
matplotlib:  '3.3.3'  (I initially tried with 3.3.2 but figure out I was not up to date after your comment)
seaborn:  '0.11.0'
and python : '3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]'
