### ISSUE TITLE
Can't Import Seaborn  --- ImportError: cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by rlphelps** [mwaskom/seaborn#2404]
OS: Kubuntu 18.04 and 20.04
Python: 3.8 and 3.9
Install has no error. 
PIL & Image installed and both import.  

Importing seaborn, results in the following error.

ImportError: cannot import name '_imaging' from 'PIL' ImportError: cannot import name '_imaging' from 'PIL'
Please help

**Comment by mwaskom** [comment]
Please show the full exception trace that you see.

Based on this information it sounds like your install of the Python Imaging Library is incomplete. That's not a direct dependency of seaborn, but I think it is for matplotlib?

**Comment by rlphelps** [comment]
After a reboot importing Seaborn in Python3.8 works.    Python3.9 responds as follows

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guest/.local/lib/python3.9/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/home/guest/.local/lib/python3.9/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/home/guest/.local/lib/python3.9/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/home/guest/.local/lib/python3.9/site-packages/seaborn/utils.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/home/guest/.local/lib/python3.9/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by mwaskom** [comment]
From that stack trace it looks like matplotlib is importing PIL (specifically `from PIL import Image`) and that's failing, I guess because you don't have it installed properly in your 3.9 environment.

This isn't directly related to seaborn and unfortunately I don't have any useful insight on debugging PIL installation, so I'm going to close here.
