### ISSUE TITLE
AttributeError:

### ISSUE THREAD

**Issue by Saman012** [mwaskom/seaborn#2428]
I have the following error message whatever the code run. How can I solve it. is it an installation error or what? 
Traceback (most recent call last):
  File "C:\Users\Home\OneDrive\Desktop\Python\numpy\howtocheckseabornversion.py", line 1, in <module>
    import seaborn as sns
  File "C:\Users\Home\OneDrive\Desktop\Python\numpy\seaborn.py", line 4, in <module>
    sns.distplot([0, 1, 2, 3, 4, 5])
AttributeError: partially initialized module 'seaborn' has no attribute 'distplot' (most likely due to a circular import)

**Comment by mwaskom** [comment]
It looks like you’ve created a file called `seaborn.py` in your working directory so when you do `import seaborn` python imports that, not the library. Rename the file and you should be fine.
