### ISSUE TITLE
urllib.error.URLError Connection timed out during seaborn load_dataset with local csv file on AIX

### ISSUE THREAD

**Issue by bergen288** [mwaskom/seaborn#2442]
Python 3.7.6 is installed on AIX7.2 server with seaborn-0.11.1 and scipy-1.6.0 packages.  In my script below, tips.csv is downloaded from https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv as my AIX server has no internet access.
```
#!/bin/python
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import seaborn as sns
fig, ax = plt.subplots()

# Load in data
tips = pd.read_csv("tips.csv")
print(tips.shape)
# tips = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sns_tips = sns.load_dataset("tips")

with PdfPages('multipage_pdf.pdf') as pdf:
    # Create violinplot
    ax.violinplot(tips["total_bill"], vert=False)
    pdf.savefig()  # saves the current figure into a pdf page
    plt.close()

    sns.violinplot(x = "total_bill", data=sns_tips)
    pdf.savefig()  # saves the current figure into a pdf page
    plt.close()
```
"tips.csv" is loaded to dataframe successfully as I can get its shape with 244 observations and 7 variables.  However, seaborn load_dataset  step failed with timeout error because of no internet access.  I wondering why it requires internet access to load local csv file and how to fix it?
 
```
seanborn_exam.py
(244, 7)
Traceback (most recent call last):
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/freeware/lib64/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/freeware/lib64/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/freeware/lib64/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/freeware/lib64/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/freeware/lib64/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/freeware/lib64/python3.7/http/client.py", line 1414, in connect
    super().connect()
  File "/opt/freeware/lib64/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/freeware/lib64/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/opt/freeware/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 78] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "seanborn_exam.py", line 11, in <module>
    sns_tips = sns.load_dataset("tips")
  File "/opt/freeware/lib/python3.7/site-packages/seaborn/utils.py", line 485, in load_dataset
    if name not in get_dataset_names():
  File "/opt/freeware/lib/python3.7/site-packages/seaborn/utils.py", line 419, in get_dataset_names
    with urlopen(url) as resp:
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/freeware/lib64/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 78] Connection timed out>
```

**Comment by mwaskom** [comment]
It looks like you have the csv file in your working directory. I think you just need to tell [`load_dataset`](https://seaborn.pydata.org/generated/seaborn.load_dataset.html) where to look for it (i.e. the `data_home` parameter).

**Comment by bergen288** [comment]
I see.  It's totally unnecessary to run ```sns.load_dataset("tips")``` step as I already have ```tips``` loaded into pandas dataframe.  I can use ```tips``` in ```sns.violinplot``` statement.

Thanks.
