### ISSUE TITLE
can't install on apple silicon M1

### ISSUE THREAD

**Issue by hkennyv** [mwaskom/seaborn#2446]
sorry if this isn't the proper place to put this but I couldn't find any other issues on this repo mentioning it.

i'm having some issues installing seaborn on my M1 Macbook Air Big Sur 11.0.1. using python 3.9.1.

```
khuynh@kmba:~ $ python3 --version
Python 3.9.1
```

Here's the output (i was able to install numpy, pandas, and matplotlib prior to this):

```
khuynh@kmba:~ $ python3 -m pip install seaborn
Collecting seaborn
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Requirement already satisfied: pandas>=0.23 in /opt/homebrew/lib/python3.9/site-packages (from seaborn) (1.2.1)
Requirement already satisfied: numpy>=1.15 in /opt/homebrew/lib/python3.9/site-packages (from seaborn) (1.19.5)
Requirement already satisfied: matplotlib>=2.2 in /opt/homebrew/lib/python3.9/site-packages (from seaborn) (3.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (8.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: six in /opt/homebrew/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /opt/homebrew/lib/python3.9/site-packages (from pandas>=0.23->seaborn) (2020.5)
Collecting scipy>=1.0
  Using cached scipy-1.6.0.tar.gz (27.3 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-13wz7h1b/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.16.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'pybind11>=2.4.3'
       cwd: None
  Complete output (226 lines):
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.10"' don't match your environment
  Collecting numpy==1.19.3
    Using cached numpy-1.19.3.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/tmpfq1alole
           cwd: /private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06
      Complete output (209 lines):
      Running from numpy source directory.
      setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Processing numpy/random/_bounded_integers.pyx.in
      Processing numpy/random/_sfc64.pyx
      Processing numpy/random/_mt19937.pyx
      Processing numpy/random/bit_generator.pyx
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_generator.pyx
      Processing numpy/random/_pcg64.pyx
      Processing numpy/random/_common.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      accelerate_info:
        libraries accelerate not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
      Library accelerate was not found. Ignoring
        libraries veclib not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
      Library veclib was not found. Ignoring
        FOUND:
          extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

        FOUND:
          extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      non-existing path in 'numpy/distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries tatlas,tatlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries tatlas,tatlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries satlas,satlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries satlas,satlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries ptf77blas,ptcblas,atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries f77blas,cblas,atlas not found in /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries f77blas,cblas,atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

        FOUND:
          extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
          extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
          define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]

      /opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.macosx-11-arm64-3.9
      creating build/src.macosx-11-arm64-3.9/numpy
      creating build/src.macosx-11-arm64-3.9/numpy/distutils
      building library "npymath" sources
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-w78irus3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-w78irus3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-w78irus3/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 508, in <module>
          setup_package()
        File "setup.py", line 500, in setup_package
          setup(**metadata)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-w78irus3/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-w78irus3/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 31, in run
          egg_info.run()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/egg_info.py", line 24, in run
          self.run_command("build_src")
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/build_src.py", line 155, in build_sources
          self.build_library_sources(*libname_info)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/build_src.py", line 288, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 658, in get_mathlib_info
          st = config_cmd.try_link('int main(void) { return 0;}')
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/config.py", line 241, in try_link
          self._check_compiler()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/command/config.py", line 80, in _check_compiler
          self.fcompiler = new_fcompiler(compiler=self.fcompiler,
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/__init__.py", line 880, in new_fcompiler
          compiler = get_default_fcompiler(plat, requiref90=requiref90,
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/__init__.py", line 851, in get_default_fcompiler
          compiler_type =  _find_existing_fcompiler(matching_compiler_types,
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/__init__.py", line 802, in _find_existing_fcompiler
          c.customize(dist)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/__init__.py", line 526, in customize
          linker_so_flags = self.flag_vars.linker_so
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/environment.py", line 37, in __getattr__
          return self._get_var(name, conf_desc)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/environment.py", line 53, in _get_var
          var = self._hook_handler(name, hook)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/__init__.py", line 705, in _environment_hook
          return hook()
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/gnu.py", line 346, in get_flags_linker_so
          flags = GnuFCompiler.get_flags_linker_so(self)
        File "/private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-install-wlqo_qfc/numpy_c046941a5aa44d68bba7480b407cff06/numpy/distutils/fcompiler/gnu.py", line 136, in get_flags_linker_so
          os.environ['MACOSX_DEPLOYMENT_TARGET'] = target
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 684, in __setitem__
          value = self.encodevalue(value)
        File "/opt/homebrew/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 756, in encode
          raise TypeError("str expected, not %s" % type(value).__name__)
      TypeError: str expected, not int
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/tmpfq1alole Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/homebrew/opt/python@3.9/bin/python3.9 /opt/homebrew/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/jc/hrnrv7f1059b2dx2kvsf4wk80000gn/T/pip-build-env-13wz7h1b/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel 'setuptools<=51.0.0' 'Cython>=0.29.18' 'numpy==1.16.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"'' 'numpy; python_version>='"'"'3.10'"'"'' 'pybind11>=2.4.3' Check the logs for full command output.
```

**NOTE:** i was able to install numpy, pandas, and matplotlib without too much issues. I had to use the following to install numpy:

```
OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install numpy --no-use-pep517
```

Here's the output of my `pip list`:

```
khuynh@kmba:~ $ python3 -m pip list
Package             Version
------------------- ---------
anyio               2.0.2
appdirs             1.4.4
appnope             0.1.2
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
Babel               2.9.0
backcall            0.2.0
bleach              3.2.1
certifi             2020.12.5
cffi                1.14.4
chardet             4.0.0
cycler              0.10.0
Cython              0.29.21
decorator           4.4.2
defusedxml          0.6.0
distlib             0.3.1
entrypoints         0.3
filelock            3.0.12
idna                2.10
iniconfig           1.1.1
ipykernel           5.4.3
ipython             7.19.0
ipython-genutils    0.2.0
jedi                0.18.0
Jinja2              2.11.2
json5               0.9.5
jsonschema          3.2.0
jupyter-client      6.1.11
jupyter-core        4.7.0
jupyter-server      1.2.2
jupyterlab          3.0.5
jupyterlab-pygments 0.1.2
jupyterlab-server   2.1.2
kiwisolver          1.3.1
MarkupSafe          1.1.1
matplotlib          3.3.3
meson               0.56.1
mistune             0.8.4
nbclassic           0.2.6
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.1.2
nest-asyncio        1.4.3
notebook            6.2.0
numpy               1.19.5
packaging           20.8
pandas              1.2.1
pandocfilters       1.4.3
parso               0.8.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.1.0
pip                 20.3.3
pluggy              0.13.1
prometheus-client   0.9.0
prompt-toolkit      3.0.10
ptyprocess          0.7.0
py                  1.10.0
pycparser           2.20
Pygments            2.7.4
pyparsing           2.4.7
pyrsistent          0.17.3
pytest              6.2.1
python-dateutil     2.8.1
pytz                2020.5
pyzmq               21.0.1
requests            2.25.1
Send2Trash          1.5.0
setuptools          51.1.1
six                 1.15.0
sniffio             1.2.0
terminado           0.9.2
testpath            0.4.4
toml                0.10.2
tornado             6.1
traitlets           5.0.5
urllib3             1.26.2
virtualenv          20.2.2
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.36.2
```

i _think_ this is related to scipy/scipy#13409

**Comment by mwaskom** [comment]
Indeed, if you look at the error trace, you run into a problem when pip tries to install scipy. I'm going to close here as this will need to be sorted out upstream. This numpy issue also seems relevant: https://github.com/numpy/numpy/issues/17807. Sorry I can't be more helpful.

**Comment by vincentwi** [comment]
+1 the whole point of this new M1 mac is to do ML and seaborn/numpy/scipy is pretty integral..

**Comment by mwaskom** [comment]
@vincentwi please do not spam multiple projects with annoying comments

**Comment by platipodium** [comment]
Confirmed working with conda (but not macports or pip) on M1

```
python      3.9.1           hcbd9b3a_2_cpython    conda-forge
```

**Comment by yawarkhalid** [comment]
> Confirmed working with conda (but not macports or pip) on M1
> 
> ```
> python      3.9.1           hcbd9b3a_2_cpython    conda-forge
> ```

Hi. Im facing the same issue with conda also. miniconda environment.

**Comment by chenxiaoyanemile** [comment]
I meet same issue on M1 Mac OS=BigSur 11.6
