### ISSUE TITLE
Seaborn cannot be used with the -OO optimization option

### ISSUE THREAD

**Issue by abaisero** [mwaskom/seaborn#2470]
Importing seaborn with a python instance which is using the -OO optimization option causes an AttributeError to be raised:

```
python -OO -c 'import seaborn'
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bais/anaconda3/lib/python3.7/site-packages/seaborn/__init__.py", line 8, in <module>
    from .distributions import *  # noqa: F401,F403
  File "/home/bais/anaconda3/lib/python3.7/site-packages/seaborn/distributions.py", line 1584, in <module>
    seealso=_core_docs["seealso"],
  File "/home/bais/anaconda3/lib/python3.7/site-packages/seaborn/_docstrings.py", line 30, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'DocstringComponents' object has no attribute 'stat'
```

It seems like a function in seaborn.distributions is being documented by assining its docstring explicitly after the function has been defined, rather than using the normal method of adding the docstring at the beginning of the function.

**Comment by mwaskom** [comment]
yes, most seaborn docstrings are built programmatically

**Comment by mwaskom** [comment]
Seems addressable with a simple change:

```diff
diff --git a/seaborn/_docstrings.py b/seaborn/_docstrings.py
index 379fa44..0869d41 100644
--- a/seaborn/_docstrings.py
+++ b/seaborn/_docstrings.py
@@ -27,7 +27,13 @@ class DocstringComponents:
         if attr in self.entries:
             return self.entries[attr]
         else:
-            return self.__getattribute__(attr)
+            try:
+                return self.__getattribute__(attr)
+            except AttributeError as err:
+                if __debug__:
+                    raise err
+                else:
+                    pass
 
     @classmethod
     def from_nested_components(cls, **kwargs):
```
