### ISSUE TITLE
BUG FacetGrid + kdeplot

### ISSUE THREAD

**Issue by cemde** [mwaskom/seaborn#2625]
Using `sns.FacetGrid` in combination with `sns.kdeplot` results in an error.

Import data loading:
``` python
import pandas as pd
import seaborn as sns
data = sns.load_dataset('exercise')
```

Just using `kdeplot` works well:

``` python
sns.kdeplot(data=data, x='pulse', hue='kind')
```

Combining it with `FacetGrid` causes an error.

``` python
g = sns.FacetGrid(data=data, col='diet')
g.map(sns.kdeplot,x='pulse', hue='kind')
```

The error:

```python
Traceback (most recent call last):
  File "/users-1/debug_sns.py", line 12, in <module>
    g.map(sns.kdeplot,x='pulse', hue='kind')
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/axisgrid.py", line 683, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/axisgrid.py", line 775, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/distributions.py", line 1696, in kdeplot
    p = _DistributionPlotter(
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/distributions.py", line 109, in __init__
    super().__init__(data=data, variables=variables)
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/_core.py", line 604, in __init__
    self.assign_variables(data, variables)
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/_core.py", line 667, in assign_variables
    plot_data, variables = self._assign_variables_longform(
  File "/users-1/user/anaconda3/envs/plot/lib/python3.9/site-packages/seaborn/_core.py", line 902, in _assign_variables_longform
    raise ValueError(err)
ValueError: Could not interpret value `pulse` for parameter `x`

```

I assume this is a bug.

**Comment by mwaskom** [comment]
Hi, it is not a bug. You can either use `FacetGrid.map` and pass x/y as positional arguments or `FacetGrid.map_dataframe` and pass them as keyword arguments. This is documented in the [api examples](http://seaborn.pydata.org/generated/seaborn.FacetGrid.html):

> The variable specification in FacetGrid.map() requires a positional argument mapping, but if the function has a data parameter and accepts named variable assignments, you can also use FacetGrid.map_dataframe().

That said, it is *strongly* recommended to use a figure-level function (i.e. `sns.displot(..., kind="kde")`) rather than manually combining `sns.FacetGrid` and `sns.kdeplot`.

**Comment by cemde** [comment]
that works well. Thanks for all the hard work! seaborn is great!
