### ISSUE TITLE
Passing vmin, vmax to LogNorm raises ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported

### ISSUE THREAD

**Issue by RylanSchaeffer** [mwaskom/seaborn#2744]
I opened [this issue on matplotlib's repository](https://github.com/matplotlib/matplotlib/issues/22518) but then realized the problem might be with Seaborn's heatmap. The problem is: suppose I try to create a heatmap like so:

```
sns.heatmap(data,
                ax=ax,
                mask=np.isnan(data),
                cmap='Spectral',
                norm=LogNorm(vmin=cutoff, vmax=1.),
                )
```

I'll get the error:

```
Traceback (most recent call last):
  File "00_prior/run_one.py", line 317, in <module>
    run_one(args)
  File "00_prior/run_one.py", line 66, in run_one
    dynamics_latex_str=dynamics_latex_str)
  File "/net/vast-storage.ib.cluster/scratch/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/00_prior/plot.py", line 47, in plot_customer_assignments_analytical_vs_monte_carlo
    norm=LogNorm(cutoff, 1.),
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/seaborn/matrix.py", line 525, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/seaborn/matrix.py", line 279, in plot
    cmap=self.cmap, **kws)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6073, in pcolormesh
    collection._scale_norm(norm, vmin, vmax)
  File "/rdma/vast-rdma/vast/fiete/rylansch/FieteLab-Recursive-Nonstationary-CRP/rncrp_venv/lib/python3.7/site-packages/matplotlib/cm.py", line 381, in _scale_norm
    "Passing parameters norm and vmin/vmax simultaneously is "
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
```

The problem persists even if I create the norm separately first.

**Comment by RylanSchaeffer** [comment]
I'm using Python 3.7.4 with seaborn 0.9.1 and matplotlib 3.5.1

**Comment by mwaskom** [comment]
seaborn 0.9.1 is several years old; can you please try on a newer version?

**Comment by RylanSchaeffer** [comment]
Works perfectly! I didn't think to check the version - my apologies!
