### ISSUE TITLE
ImportError: DLL load failed while importing qhull: The specified module could not be found.

### ISSUE THREAD

**Issue by Code4SAFrankie** [mwaskom/seaborn#2796]
Getting this error when importing seaborn

ImportError: DLL load failed while importing qhull: The specified module could not be found.

>>> import seaborn as sns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\rcmod.py", line 7, in <module>
    from . import palettes
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\seaborn\utils.py", line 10, in <module>
    from scipy import stats
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\stats\__init__.py", line 441, in <module>
    from .stats import *
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\stats\stats.py", line 37, in <module>
    from scipy.spatial.distance import cdist
  File "C:\WPy64-3980\python-3.9.8.amd64\lib\site-packages\scipy\spatial\__init__.py", line 98, in <module>
    from .qhull import *
ImportError: DLL load failed while importing qhull: The specified module could not be found.

Using seaborn‑0.11.0‑py3‑none‑any.whl on Python 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by mwaskom** [comment]
Hi, if you look through the stacktrace you can see that this error is ultimately coming out of scipy, so I don't think there's anything that can be done on the seaborn side.
