### ISSUE TITLE
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?

### ISSUE THREAD

**Issue by eelir** [mwaskom/seaborn#3052]
I have been trying to run any example from seaborn tutorial and all throw the same error. I am using python 3.10 and pycharm as editor that takes care of venv. I am not including any code as as soon as sns tries to plot something the error is thrown. Here is the error traceback output:

```Traceback (most recent call last):
  File "/Users/u/Documents/workspace/DeezerVeezer/main.py", line 4, in <module>
    sns.pairplot(df, hue="species")
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/seaborn/axisgrid.py", line 2114, in pairplot
    grid = PairGrid(data, vars=vars, x_vars=x_vars, y_vars=y_vars, hue=hue,
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/seaborn/axisgrid.py", line 1274, in __init__
    fig = plt.figure(figsize=figsize)
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 771, in figure
    manager = new_figure_manager(
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 346, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 336, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod()) and
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 206, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/Users/u/Documents/workspace/DeezerVeezer/venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 266, in switch_backend
    canvas_class = backend_mod.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?```

**Comment by mwaskom** [comment]
If you look through the traceback, it's entering matplotlib from seaborn on a simple line:

```python
    fig = plt.figure(figsize=figsize)
```

That suggests it's not anything seaborn is doing.

And indeed, if you search the text of the error message on their issue tracker, you'll find a relevant report: https://github.com/matplotlib/matplotlib/issues/23911

**Comment by mwaskom** [comment]
Closing as upstream issue.
