### ISSUE TITLE
python3.6 import error

### ISSUE THREAD

**Issue by WaterHyacinthInNANHU** [mwaskom/seaborn#3067]
Hi! I have trouble importing seaborn in py3.6
```
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import seaborn
```

```
Traceback (most recent call last):
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1429, in <module>
    fontManager = json_load(_fmcache)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1013, in json_load
    return json.load(fh, object_hook=_json_decode)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3429 column 25 (char 90140)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/seaborn/rcmod.py", line 7, in <module>
    from . import palettes
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/seaborn/palettes.py", line 9, in <module>
    from .utils import desaturate, get_color_cycle
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/seaborn/utils.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/contour.py", line 16, in <module>
    import matplotlib.font_manager as font_manager
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1431, in <module>
    _rebuild()
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/font_manager.py", line 1425, in _rebuild
    json_dump(fontManager, _fmcache)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/font_manager.py", line 997, in json_dump
    with cbook._lock_path(filename), open(filename, 'w') as fh:
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/yan/anaconda3/envs/ML3.6/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 1810, in _lock_path
    lock_path))
TimeoutError: Lock error: Matplotlib failed to acquire the following lock file:
    /home/yan/.cache/matplotlib/fontlist-v330.json.matplotlib-lock
This maybe due to another process holding this lock file.  If you are sure no
other Matplotlib process is running, remove this file and try again.
```

**Comment by WaterHyacinthInNANHU** [comment]
Fixed after delete `/home/yan/.cache/matplotlib/fontlist-v330.json.matplotlib-lock` . It's related to the matplotlib.
