### ISSUE TITLE
relplot fails for this specific dataframe when updating numpy to 1.24

### ISSUE THREAD

**Issue by ClementPinard** [mwaskom/seaborn#3199]
Hi,

thanks for your work on this superb library !
I have been having trouble using relplot since I updated my version ot numpy 1.24 (before it was 1.23.4)

The example for relplot does not work anymore if we add the `kind="line"` option

```python
import seaborn as sns
tips = sns.load_dataset("tips")
sns.relplot(data=tips, x="total_bill", y="tip", hue="day", kind="line")
```

We then get the following stacktrace
```
Traceback (most recent call last):
  File "/home/clementpinard/test.py", line 4, in <module>
    sns.relplot(data=tips, x="total_bill", y="tip", hue="day", kind="line")
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/seaborn/relational.py", line 955, in relplot
    g.map_dataframe(func, **plot_kws)
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/seaborn/axisgrid.py", line 819, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/seaborn/axisgrid.py", line 848, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/seaborn/relational.py", line 645, in lineplot
    p.plot(ax, kwargs)
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/seaborn/relational.py", line 489, in plot
    func(
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5367, in fill_between
    return self._fill_between_x_or_y(
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5272, in _fill_between_x_or_y
    ind, dep1, dep2 = map(
  File "/home/clementpinard/miniconda3/lib/python3.9/site-packages/numpy/ma/core.py", line 2360, in masked_invalid
    return masked_where(~(np.isfinite(getdata(a))), a, copy=copy)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

According to a quick google search I made, this occurs when trying to use object dtypes in numpy where you shouldn't, but it does not get any clearer than that.

Note that if we remove the `kind="line"` option,the error disappear

Here a my current version for these libraries :

seaborn : 0.12.1
matplotlib : 3.6.2
numpy : 1.24

Note that if we downgrade numpy to 1.23.X, it works as expected.

To be honest, I'm not sure this is an issue with seaborn, could be with matplotlib or even in numpy. But in these case, I don't have a simple bug repro to share with them.

**Comment by mwaskom** [comment]
See https://github.com/mwaskom/seaborn/issues/3192

**Comment by mwaskom** [comment]
Numpy issue is https://github.com/numpy/numpy/issues/22826

**Comment by ClementPinard** [comment]
Ah thanks ! sorry about not searching thoroughly.

Thanks !

Clément
