### ISSUE TITLE
Violinplot returns "array is 0-dimensional" error

### ISSUE THREAD

**Issue by mikeheffler** [mwaskom/seaborn#3201]
Calling violinplot() returns error "IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed." Boxplot() with identical arguments works normally.

For background below, "file" is a pandas dataframe read from an excel sheet, 'Pre/Post' is a column of categorial entries of either "Pre" or "Post" values, 'LOS_Min' is a column of continuous float values. 

Command: 
>>> sns.violinplot(data = file, x = 'Pre/Post' , y = 'LOS_Min').set( title = 'ED LOS before and after intervention', xlabel='' , ylabel = 'ED LOS (min)')

Full traceback:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/categorical.py", line 2313, in violinplot
    plotter.plot(ax)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/categorical.py", line 1419, in plot
    self.draw_violins(ax)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/seaborn/categorical.py", line 1165, in draw_violins
    fill_func(support,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5349, in fill_betweenx
    return self._fill_between_x_or_y(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 5263, in _fill_between_x_or_y
    for idx0, idx1 in cbook.contiguous_regions(where):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 1333, in contiguous_regions
    idx, = np.nonzero(mask[:-1] != mask[1:])
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

**Comment by mwaskom** [comment]
It is impossible to answer without a reproducible example.

**Comment by mikeheffler** [comment]
My apologies, I missed that part. The below code is similar and reproduces the problem in python 3.10

>>> import pandas as pd
>>> import seaborn as sns
>>> import matplotlib.pyplot as plt
>>>
>>> data = {'Pre/Post':['Pre', 'Pre', 'Pre', 'Pre', 'Post', 'Post', 'Post', 'Post'], 'LOS':[5, 10, 15, 20, 7.5, 12.5, 17.5, 22.5]}
>>> df = pd.DataFrame.from_dict(data)
>>> df
>>>
>>> sns.boxplot(data=df, x='Pre/Post', y='LOS')
>>> plt.show()
>>>
>>> sns.violinplot(data=df, x='Pre/Post', y='LOS')

Let me know if that is sufficient or if you need more detail

**Comment by mwaskom** [comment]
Thanks, however, I cannot reproduce your issue:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/315810/209239368-9085f318-e35f-45e9-8a6e-5a519a4d6333.png">

**Comment by mikeheffler** [comment]
I appreciate the quick replies! 

I hate to say it, but I uninstalled seaborn and matplotlib and re-installed and it seems to be working... Glad it was a simple fix in the end
