### ISSUE TITLE
TypeError: vars() argument must have __dict__ attribute

### ISSUE THREAD

**Issue by snorthman** [mwaskom/seaborn#3286]
Using 3.10, using a new environment, I did:

```commandline
pip install seaborn[stats] 
```
In main.py:

```python
import seaborn as sns

sns.set_theme(context="paper")
fmri = sns.load_dataset("fmri")
g = sns.relplot(
    data=fmri, kind="line",
    x="timepoint", y="signal",
    hue="event", style="event", col="region",
    height=3.5, aspect=.8,
)
```

Run in cmd:
```commandline
~\python.exe ~/main.py
Traceback (most recent call last):
  File "~\main.py", line 7, in <module>
    g = sns.relplot(
  File "~\venv\lib\site-packages\seaborn\relational.py", line 946, in relplot
    g = FacetGrid(
  File "~\venv\lib\site-packages\seaborn\axisgrid.py", line 447, in __init__
    fig = plt.figure(figsize=figsize)
  File "~\venv\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "~\venv\lib\site-packages\matplotlib\pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "~\venv\lib\site-packages\matplotlib\pyplot.py", line 382, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "~\venv\lib\site-packages\matplotlib\pyplot.py", line 360, in _warn_if_gui_out_of_main_thread
    if _get_required_interactive_framework(_get_backend_mod()):
  File "~\venv\lib\site-packages\matplotlib\pyplot.py", line 208, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "~\venv\lib\site-packages\matplotlib\pyplot.py", line 331, in switch_backend
    manager_pyplot_show = vars(manager_class).get("pyplot_show")
TypeError: vars() argument must have __dict__ attribute

Process finished with exit code 1
```

Looks like a matplotlib problem, but is it really? `manager_class` here was None.

**Comment by mwaskom** [comment]
> Looks like a matplotlib problem, but is it really? 

Well, why do you think it's a seaborn problem? An issue this basic would have shown up in seaborn tests by now. What happens when you try to make matplotlib plots without seaborn?

**Comment by mwaskom** [comment]
I'm going to close as this isn't reproducible or systemic and I don't see any evidence that it's a seaborn issue per se. Happy to reopen if demonstrated otherwise though.
