### ISSUE TITLE
ValueError because of Multi-dimensional indexing for KDE from displot()

### ISSUE THREAD

**Issue by Michael-E-Rose** [mwaskom/seaborn#3312]
I think I came across a bug with KDEs. Let me show you an example from https://seaborn.pydata.org/generated/seaborn.displot.html

```
import pandas as pd
pd.__version__
Out[3]: '2.0.0'
import seaborn as sns
Backend TkAgg is interactive backend. Turning interactive mode on.
sns.__version__
Out[5]: '0.12.2'
penguins = sns.load_dataset("penguins")
sns.displot(data=penguins, x="flipper_length_mm", hue="species", kind="kde")
Traceback (most recent call last):
  File "C:\Program Files\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-140e71381471>", line 1, in <module>
    sns.displot(data=penguins, x="flipper_length_mm", hue="species", kind="kde")
  File "C:\Program Files\Python\Python39\lib\site-packages\seaborn\distributions.py", line 2235, in displot
    p.plot_univariate_density(**kde_kws)
  File "C:\Program Files\Python\Python39\lib\site-packages\seaborn\distributions.py", line 999, in plot_univariate_density
    artist, = ax.plot(support, density, **artist_kws)
  File "C:\Program Files\Python\Python39\lib\site-packages\matplotlib\axes\_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\Program Files\Python\Python39\lib\site-packages\matplotlib\axes\_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\matplotlib\axes\_base.py", line 490, in _plot_args
    x = _check_1d(xy[0])
  File "C:\Program Files\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 1362, in _check_1d
    ndim = x[:, None].ndim
  File "C:\Users\rosm\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexes\base.py", line 5198, in __getitem__
    disallow_ndim_indexing(result)
  File "C:\Users\rosm\AppData\Roaming\Python\Python39\site-packages\pandas\core\indexers\utils.py", line 343, in disallow_ndim_indexing
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

**Comment by thuiop** [comment]
This behaviour was indeed removed in pandas 2.0 ; for the time being I guess the best course is to stick with 1.5.3, although the issue should be addressed in seaborn in the end.

**Comment by mwaskom** [comment]
I can't replicate

<img width="479" alt="image" src="https://user-images.githubusercontent.com/315810/229779924-5aa7f573-484b-4296-8a0d-578554bf6da5.png">

**Comment by mwaskom** [comment]
Your stack trace is going through matplotlib code. What version of matplotlib are you on? I have 3.7.0 in the environment where this works. Also numpy 1.24.2.

**Comment by thuiop** [comment]
Oh right, it seems it was taken care of a long time ago (see matplotlib/matplotlib#16295)

**Comment by Michael-E-Rose** [comment]
It works with current matplotlib. I used to use matplotlib 3.4.0.

**Comment by Neevjain004** [comment]
I'm on matplotlib version 3.5.1 still getting the same error

**Comment by akib35** [comment]
Yeah, It's not working in 3.5.1

**Comment by mwaskom** [comment]
The latest version of matplotlib is 3.7.1.
