### ISSUE TITLE
facet plots failing after pandas upgraded to 2.0

### ISSUE THREAD

**Issue by ags-dy** [mwaskom/seaborn#3326]
The pyproject.toml file in the repo has:
  "pandas>=1.2",

and this morning my system updated pandas to version 2.0.  I now get this error:

```    
/usr/lib/python3/dist-packages/seaborn/_decorators.py:46: in inner_f
    return f(**kwargs)
/usr/lib/python3/dist-packages/seaborn/relational.py:1036: in relplot
    g.map_dataframe(func, **plot_kws)
/usr/lib/python3/dist-packages/seaborn/axisgrid.py:790: in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
/usr/lib/python3/dist-packages/seaborn/axisgrid.py:819: in _facet_plot
    func(*plot_args, **plot_kwargs)
/usr/lib/python3/dist-packages/seaborn/_decorators.py:46: in inner_f
    return f(**kwargs)
/usr/lib/python3/dist-packages/seaborn/relational.py:710: in lineplot
    p.plot(ax, kwargs)
/usr/lib/python3/dist-packages/seaborn/relational.py:471: in plot
    for sub_vars, sub_data in self.iter_data(grouping_vars, from_comp_data=True):
/usr/lib/python3/dist-packages/seaborn/_core.py:983: in iter_data
    data = self.comp_data
/usr/lib/python3/dist-packages/seaborn/_core.py:1054: in comp_data
    with pd.option_context('mode.use_inf_as_null', True):
/usr/local/lib/python3.10/dist-packages/pandas/_config/config.py:441: in __enter__
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
/usr/local/lib/python3.10/dist-packages/pandas/_config/config.py:441: in <listcomp>
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
/usr/local/lib/python3.10/dist-packages/pandas/_config/config.py:135: in _get_option
    key = _get_single_key(pat, silent)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

pat = 'mode.use_inf_as_null', silent = True

    def _get_single_key(pat: str, silent: bool) -> str:
        keys = _select_options(pat)
        if len(keys) == 0:
            if not silent:
                _warn_if_deprecated(pat)
>           raise OptionError(f"No such keys(s): {repr(pat)}")
E           pandas._config.config.OptionError: No such keys(s): 'mode.use_inf_as_null'

/usr/local/lib/python3.10/dist-packages/pandas/_config/config.py:121: OptionError
```

which I assume is due to the upgrade.

**Comment by mwaskom** [comment]
Well what version of seaborn are you using? What are you actually doing to get this error? Please provide a [valid bug report](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs) or I cannot help.

**Comment by ags-dy** [comment]
Sorry!  Here is a minimal example using code from the docs.

ubuntu 20.04
python 3.10
seaborn v0.11.2
pandas v2.0

From this page:
https://seaborn.pydata.org/generated/seaborn.relplot.html#

I used the replot example code:

```
import seaborn as sns
import matplotlib.pyplot as plt

fmri = sns.load_dataset("fmri")

sns.relplot(
    data=fmri,
    x="timepoint",
    y="signal",
    col="region",
    hue="event",
    style="event",
    kind="line",
)

plt.show()

```

and it gives the same error I was getting in my custom code:


```
    sns.relplot(
  File "/usr/lib/python3/dist-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/relational.py", line 1036, in relplot
    g.map_dataframe(func, **plot_kws)
  File "/usr/lib/python3/dist-packages/seaborn/axisgrid.py", line 790, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/axisgrid.py", line 819, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/relational.py", line 710, in lineplot
    p.plot(ax, kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/relational.py", line 471, in plot
    for sub_vars, sub_data in self.iter_data(grouping_vars, from_comp_data=True):
  File "/usr/lib/python3/dist-packages/seaborn/_core.py", line 983, in iter_data
    data = self.comp_data
  File "/usr/lib/python3/dist-packages/seaborn/_core.py", line 1054, in comp_data
    with pd.option_context('mode.use_inf_as_null', True):
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/_config/config.py", line 441, in __enter__
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/_config/config.py", line 441, in <listcomp>
    self.undo = [(pat, _get_option(pat, silent=True)) for pat, val in self.ops]
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/_config/config.py", line 135, in _get_option
    key = _get_single_key(pat, silent)
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/_config/config.py", line 121, in _get_single_key
    raise OptionError(f"No such keys(s): {repr(pat)}")
pandas._config.config.OptionError: No such keys(s): 'mode.use_inf_as_null'
```


I think the error is due to the updates to nullable types in pandas 2.0

https://towardsdatascience.com/whats-new-in-pandas-2-0-5df366eb0197

**Comment by ags-dy** [comment]
ah ok, thanks.  I updated seaborn to 0.12.2 and left pandas at 2.0 and still get an error with that example code:

```
Traceback (most recent call last):
  File "/home/host_user/work/src/common/bencher/bencher/example/seaborn_bug.py", line 6, in <module>
    sns.relplot(
  File "/home/host_user/.local/lib/python3.10/site-packages/seaborn/relational.py", line 955, in relplot
    g.map_dataframe(func, **plot_kws)
  File "/home/host_user/.local/lib/python3.10/site-packages/seaborn/axisgrid.py", line 819, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "/home/host_user/.local/lib/python3.10/site-packages/seaborn/axisgrid.py", line 848, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/home/host_user/.local/lib/python3.10/site-packages/seaborn/relational.py", line 645, in lineplot
    p.plot(ax, kwargs)
  File "/home/host_user/.local/lib/python3.10/site-packages/seaborn/relational.py", line 459, in plot
    lines = ax.plot(sub_data["x"], sub_data["y"], **kws)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 1632, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 487, in _plot_args
    x = _check_1d(xy[0])
  File "/usr/lib/python3/dist-packages/matplotlib/cbook/__init__.py", line 1327, in _check_1d
    ndim = x[:, None].ndim
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1038, in __getitem__
    return self._get_with(key)
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1053, in _get_with
    return self._get_values_tuple(key)
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1087, in _get_values_tuple
    disallow_ndim_indexing(result)
  File "/home/host_user/.local/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 343, in disallow_ndim_indexing
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```
