### ISSUE TITLE
lineplot bug: raises Keyerror: 'y' if y column contains all NaNs

### ISSUE THREAD

**Issue by shawnboltz** [mwaskom/seaborn#3351]
Also raises KeyError: 'x' if x column contains all NaNs. This also affects relplot if `kind="line"`, but not if `kind="scatter"`

**Description**
When making a lineplot, it will raise at the pandas level with a KeyError: 'y' (or x) if the column corresponding to y or x contains all NaNs. It looks like this is because the column is getting dropped during the process of collecting the subdata. Where this really becomes problematic is if you are doing a relplot and the data for one of the subplots happens to have all NaNs for one of the subsets when passing the `row` or `col` kwargs.

This is a new behavior since version 0.12.x? It works in 0.11.2.

**To Reproduce**
```
In [1]: import numpy as np
   ...: import pandas as pd
   ...: import seaborn as sns

In [2]: data1 = {"A": np.arange(100), "B": np.arange(100) * 2 + np.random.random(100)}
   ...: data1["category"] = ["1"] * 100
   ...: data2 = {"A": np.arange(100), "B": np.arange(100) * 2 + np.random.random(100)}
   ...: data2["category"] = ["2"] * 100
   ...: data3 = {"A": np.arange(100), "B": np.arange(100) * 2 + np.random.random(100)}
   ...: data3["category"] = ["3"] * 100
   ...: df = pd.concat(pd.DataFrame(data=x, columns=["category", "A", "B"]) for x in [data1, data2, data3]).reset_index()
   ...: df.head()
Out[2]:
   index category  A         B
0      0        1  0  0.133222
1      1        1  1  2.187327
2      2        1  2  4.244726
3      3        1  3  6.945193
4      4        1  4  8.063022

In [3]: df.loc[df["category"] == "2", "B"] = np.NaN

In [4]: sns.lineplot(df, x="A", y="B", hue="category")  # This works
Out[4]: <AxesSubplot:xlabel='A', ylabel='B'>

In [5]: sns.relplot(df, x="A", y="B", col="category")  # This also works
Out[5]: <seaborn.axisgrid.FacetGrid at 0x1c0587da2b0>

In [6]: sns.lineplot(df.loc[df["category"] == "2"], x="A", y="B", hue="category")  # This doesn't
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3628             try:
-> 3629                 return self._engine.get_loc(casted_key)
   3630             except KeyError as err:

~\Anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

~\Anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'y'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-0283d3677017> in <module>
----> 1 sns.lineplot(df.loc[df["category"] == "2"], x="A", y="B", hue="category")  # This doesn't

~\Anaconda3\lib\site-packages\seaborn\relational.py in lineplot(data, x, y, hue, size, style, units, palette, hue_order, hue_norm, sizes, size_order, size_norm, dashes, markers, style_order, estimator, errorbar, n_boot, seed, orient, sort, err_style, err_kws, legend, ci, ax, **kwargs)
    643     kwargs["color"] = _default_color(ax.plot, hue, color, kwargs)
    644
--> 645     p.plot(ax, kwargs)
    646     return ax
    647

~\Anaconda3\lib\site-packages\seaborn\relational.py in plot(self, ax, kws)
    457                     lines.extend(ax.plot(unit_data["x"], unit_data["y"], **kws))
    458             else:
--> 459                 lines = ax.plot(sub_data["x"], sub_data["y"], **kws)
    460
    461             for line in lines:

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3503             if self.columns.nlevels > 1:
   3504                 return self._getitem_multilevel(key)
-> 3505             indexer = self.columns.get_loc(key)
   3506             if is_integer(indexer):
   3507                 indexer = [indexer]

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3629                 return self._engine.get_loc(casted_key)
   3630             except KeyError as err:
-> 3631                 raise KeyError(key) from err
   3632             except TypeError:
   3633                 # If we have a listlike key, _check_indexing_error will raise

KeyError: 'y'



In [7]: sns.relplot(df, x="A", y="B", col="category", kind="line")  # This also doesn't
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...

KeyError: 'y'
```

**Expected Behavior**
For lineplot: it should either generate an empty plot or raise an error explaining that the data only contain NaNs
For relplot: it should just produce an empty plot for affected subplots

**Versioning**
Seaborn: 0.12.2

**Comment by lukaszkadlubowski** [comment]
I think I have a similar problem.

# Example

## Code

```python
# %%
import numpy as np
import seaborn as sns

# %%
fmri = (
    sns.load_dataset("fmri")
    .query("region == 'parietal'")
    .query("subject == 's1' or subject == 's2' or subject == 's3'")
    .drop(columns=["region"])
    .sort_values(by=["subject"])
)
# change all data for subject s2 to NaN
fmri.loc[(fmri["subject"] == "s2"), "signal"] = np.nan
# introduce a gap in subject s1 data
fmri.loc[
    (fmri["subject"] == "s1")
    & (fmri["timepoint"] > 6)
    & (fmri["timepoint"] < 9),
    "signal",
] = np.nan
print(fmri.groupby(["subject", "event"]).agg(["count", "size"]))

# %%
sns.relplot(
    data=fmri,
    kind="line",
    x="timepoint",
    y="signal",
    hue="event",
    col="subject",
)
```

## Summary of data to be plotted

Resulting from the code above. s2 data is all changed deliberately to NaN and a gap is introduced in s1 data.

```
              timepoint      signal     
                  count size  count size
subject event
s1      cue          19   19     17   19
        stim         19   19     17   19
s2      cue          19   19      0   19
        stim         19   19      0   19
s3      cue          19   19     19   19
        stim         19   19     19   19
```

## The output I see

<img width="755" alt="output1" src="https://user-images.githubusercontent.com/65432554/235501030-c6cddd4b-8d11-4914-bdc2-28a4499e2586.png">

followed by the error:

```
Traceback (most recent call last):
  File "D:\app\venv310\lib\site-packages\pandas\core\indexes\base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'y'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\app\experiments\seaborn\allnans.py", line 25, in <module>
    sns.relplot(
  File "D:\app\swdeps\seaborn_fork\seaborn\relational.py", line 922, in relplot
    g.map_dataframe(func, **plot_kws)
  File "D:\app\swdeps\seaborn_fork\seaborn\axisgrid.py", line 819, in map_dataframe
    self._facet_plot(func, ax, args, kwargs)
  File "D:\app\swdeps\seaborn_fork\seaborn\axisgrid.py", line 848, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "D:\app\swdeps\seaborn_fork\seaborn\relational.py", line 612, in lineplot
    p.plot(ax, kwargs)
  File "D:\app\swdeps\seaborn_fork\seaborn\relational.py", line 426, in plot
    lines = ax.plot(sub_data["x"], sub_data["y"], **kws)
  File "D:\app\venv310\lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\app\venv310\lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'y'
```

## Possible workaround

This can be "solved" by dropping nans from the data to be plotted:

```python
sns.relplot(data=fmri.dropna(), ...)
```

result: no error and the figure like below:

<img width="536" alt="output2" src="https://user-images.githubusercontent.com/65432554/235502210-05b70bc1-0332-42cc-a741-1cdfba1bfd46.png">

## Expected behavior

There are still two problems with the `dropna()` workaround:
- for any reason, I may want to keep the empty facet to emphasize that there is no data for a given case
- no gap is plotted in subject s1 data (the problem discussed before)

<img width="787" alt="expected" src="https://user-images.githubusercontent.com/65432554/235500129-f65e56e6-4eaa-4835-ae81-766b20791366.png">

## Package versions

seaborn: latest commit https://github.com/mwaskom/seaborn/commit/eb2b5a21dfc9a20f2eeec100490d5c014e689c65
matplotlib==3.7.1

# Possible fix (?)

## Description

The problem of filling gaps introduced by NaNs was partially addressed in the past:
- https://github.com/mwaskom/seaborn/issues/1552
- https://github.com/mwaskom/seaborn/issues/2120
- https://github.com/mwaskom/seaborn/pull/2273
- https://github.com/mwaskom/seaborn/issues/2272

The conclusion was that it is somehow tricky to implement.

## My modifications

I made two modifications in my fork which address this problem:

### Modification 1

Based on the comment:

https://github.com/mwaskom/seaborn/blob/eb2b5a21dfc9a20f2eeec100490d5c014e689c65/seaborn/relational.py#L382

```
        # TODO How to handle NA? We don't want NA to propagate through to the
        # estimate/CI when some values are present, but we would also like
        # matplotlib to show "gaps" in the line when all values are missing.
        # This is straightforward absent aggregation, but complicated with it.
        # If we want to use nas, we need to conditionalize dropna in iter_data.
```

and I did exactly that: I used `dropna=False` when calling `iter_data` in `_LinePlotter.plot()`:

https://github.com/mwaskom/seaborn/blob/eb2b5a21dfc9a20f2eeec100490d5c014e689c65/seaborn/relational.py#L390

```diff
-        for sub_vars, sub_data in self.iter_data(grouping_vars, from_comp_data=True):
+        for sub_vars, sub_data in self.iter_data(grouping_vars, from_comp_data=True, dropna=False):
```

### Modification 2

The line responsible for not including `y` in the `self.variables` dictionary of `VectorPlotter` class if there are only NaNs in the `y` column:

https://github.com/mwaskom/seaborn/blob/eb2b5a21dfc9a20f2eeec100490d5c014e689c65/seaborn/_oldcore.py#L973

I added `y` as an exception in dictionary comprehension:

```diff
        variables = {
            var: name
            for var, name in variables.items()
-            if plot_data[var].notnull().any()
+            if plot_data[var].notnull().any() or var == 'y'
        }
```


## Exemplary result

```python
import numpy as np
import seaborn as sns
fmri = sns.load_dataset("fmri")
fmri.loc[((fmri["timepoint"] > 3) & (fmri["timepoint"] < 9)), "signal"] = np.nan
sns.relplot(data=fmri, x="timepoint", y="signal", kind="line")
```

### Before modification (actual behavior)

<img width="245" alt="before1" src="https://user-images.githubusercontent.com/65432554/235508730-19255bb2-a6e9-4e2c-984b-e52d50800941.png">

### After modification (expected behavior)

<img width="245" alt="after1" src="https://user-images.githubusercontent.com/65432554/235508927-ee3dabeb-5585-44d4-a6f9-ecf7b691a70c.png">

here it works, not without introducing warnings, however:

```
D:\app\swdeps\seaborn_fork\seaborn\algorithms.py:100: RuntimeWarning: Mean of empty slice
  boot_dist.append(f(*sample, **func_kwargs))
D:\app\venv310\lib\site-packages\numpy\lib\nanfunctions.py:1559: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a,
```

## Comment

This kinda works, but breaks several unit tests and probably breaks other use cases (?). I cannot assess the difficulty of implementing the real solution without deeper knowledge of the library and the codebase.

Also the problem is present in the new objects interface, hopefully will be addressed in the future.

Many thanks to the creator of the library and contributors!

**Comment by leoluecken** [comment]
Hey everybody, I encountered this as well. Here's a very simple reproduction:
```python
import numpy as np
import seaborn as sns
df = {"val":[np.NaN, np.NaN], "par":[1, 2]}
sns.lineplot(df, x="par", y="val")
```
This raises `KeyError: 'y'`

**Comment by MaozGelbart** [comment]
Tried all these repros on current master branch, no error is raised.

**Comment by shawnboltz** [comment]
@MaozGelbart Sorry for the delayed response. I can confirm that this appears to be fixed in the current master branch.
