### ISSUE TITLE
Seaborn fails with flask server on Mac OS, python 2.7.8 due to _winreg not found

### ISSUE THREAD

**Issue by kwantopia** [mwaskom/seaborn#475]
The external module six.py in seaborn is somehow trying to look for _winreg on my Mac OS and as a result crashing my Flask app server.

**Comment by kwantopia** [comment]
```
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "run_local.py", line 30, in <module>
    app.run(host='0.0.0.0', debug=True)
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/werkzeug/serving.py", line 622, in run_simple
    reloader_type)
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/werkzeug/_reloader.py", line 269, in run_with_reloader
    reloader.run()
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/werkzeug/_reloader.py", line 159, in run
    for filename in chain(_iter_module_files(), self.extra_files):
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/werkzeug/_reloader.py", line 70, in _iter_module_files
    for package_path in getattr(module, '__path__', ()):
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/seaborn/external/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/seaborn/external/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/Users/kwanhonglee/Documents/workspace/companies/flask/lib/python2.7/site-packages/seaborn/external/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named _winreg
```

**Comment by mwaskom** [comment]
Can you import seaborn normally or is this something that only happens when using flask?

**Comment by kwantopia** [comment]
It only happens when using flask.  It works fine if it was run as a separate standalone script.

**Comment by mwaskom** [comment]
Looks like it's got something to do with the flask reloader? I'm not sure.

**Comment by kwantopia** [comment]
Its due to the six.py external that gets added when pip installing seaborn.  If I comment out the MovedModule("winreg", "_winreg") in external/six.py things work fine.

**Comment by mwaskom** [comment]
Not sure what to tell you but that file is just copied in directly (http://pythonhosted.org/six/) and so it's not likely to have anything to do with seaborn.
