### ISSUE TITLE
Empty argument to tsplot leads to UnboundLocalError

### ISSUE THREAD

**Issue by anntzer** [mwaskom/seaborn#506]
Arguably a not-so-important edge case, so I'm just mentioning it:
```
$ python -c 'from seaborn import tsplot; tsplot([])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/seaborn/timeseries.py", line 255, in tsplot
    ax.set_xlim(x.min(), x.max())
UnboundLocalError: local variable 'x' referenced before assignment
```
(seaborn 0.5.1)

**Comment by mwaskom** [comment]
Ah yes, I'd say this is about 20th on the list of reasons `tsplot` is a pain in the ass.
