### ISSUE TITLE
Can not install seaborn when google-api-python-client is installed.

### ISSUE THREAD

**Issue by orena1** [mwaskom/seaborn#549]
First I install google-api-python-client
```bash
oren.amsalem@bream ~/Local/teamviewer $ pip install --upgrade google-api-python-client
Collecting google-api-python-client
  Using cached google-api-python-client-1.4.0.tar.gz
Requirement already up-to-date: httplib2>=0.8 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: oauth2client>=1.4.6 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: six>=1.6.1 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: uritemplate>=0.6 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from google-api-python-client)
Requirement already up-to-date: pyasn1==0.1.7 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client)
Requirement already up-to-date: pyasn1-modules==0.0.5 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client)
Requirement already up-to-date: rsa==3.1.4 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from oauth2client>=1.4.6->google-api-python-client)
Requirement already up-to-date: simplejson>=2.5.0 in /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages (from uritemplate>=0.6->google-api-python-client)
Installing collected packages: google-api-python-client
  Running setup.py install for google-api-python-client
Successfully installed google-api-python-client-1.4.0
```
Than I can not install seaborn
```bash
oren.amsalem@bream ~/Local/teamviewer $ pip install --upgrade seaborn
Collecting seaborn
  Using cached seaborn-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-qdo4vR/seaborn/setup.py", line 65, in <module>
        install_requires = check_dependencies()
      File "/tmp/pip-build-qdo4vR/seaborn/setup.py", line 53, in check_dependencies
        import pandas
      File "/home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 45, in <module>
        from pandas.io.api import *
      File "/home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/pandas/io/api.py", line 15, in <module>
        from pandas.io.gbq import read_gbq
      File "/home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/pandas/io/gbq.py", line 39, in <module>
        if LooseVersion(_GOOGLE_API_CLIENT_VERSION >= '1.2.0'):
      File "/home/users/oren.amsalem/anaconda/lib/python2.7/distutils/version.py", line 265, in __init__
        self.parse(vstring)
      File "/home/users/oren.amsalem/anaconda/lib/python2.7/distutils/version.py", line 274, in parse
        self.component_re.split(vstring))
    TypeError: expected string or buffer
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qdo4vR/seaborn
```
But if I remove google-api-python-client
```bash
oren.amsalem@bream ~/Local/teamviewer $ pip uninstall  google-api-python-client
Uninstalling google-api-python-client-1.4.0:
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/apiclient/__init__.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/apiclient/__init__.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/google_api_python_client-1.4.0-py2.7.egg-info
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/__init__.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/__init__.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/channel.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/channel.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/discovery.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/discovery.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/errors.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/errors.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/http.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/http.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/mimeparse.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/mimeparse.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/model.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/model.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/sample_tools.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/sample_tools.pyc
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/schema.py
  /home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/googleapiclient/schema.pyc
Proceed (y/n)? y
  Successfully uninstalled google-api-python-client-1.4.0
```
I can install seaborn
```bash
oren.amsalem@bream ~/Local/teamviewer $ pip install --upgrade seaborn
Collecting seaborn
  Using cached seaborn-0.5.1.tar.gz
Installing collected packages: seaborn
  Running setup.py install for seaborn
Successfully installed seaborn-0.5.1
oren.amsalem@bream ~/Local/teamviewer $ 
```

Thanks

**Comment by mwaskom** [comment]
Weird!

**Comment by mwaskom** [comment]
It's possible this is a bug in pandas actually:

```python
File "/home/users/oren.amsalem/anaconda/lib/python2.7/site-packages/pandas/io/gbq.py", line 39, in <module>
        if LooseVersion(_GOOGLE_API_CLIENT_VERSION >= '1.2.0'):
```

I would have thought that would be

```python
        if LooseVersion(_GOOGLE_API_CLIENT_VERSION) >= '1.2.0':
```

When you have google-api-client installed, can you import pandas?

**Comment by orena1** [comment]
You are right..
I can not import pandas..

**Comment by mwaskom** [comment]
Great, I'd open an issue on the pandas tracker if you haven't already; this looks like a simple bug.

**Comment by orena1** [comment]
I did not open an issue.. Please open one. 

Thank You,
Oren.
