### ISSUE TITLE
Fix random failure of logistic regression test

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#618]
Probably just poisson variation but it feels like this has been failing more often (weirdly, almost always on the Python 3.4 build).

```python
======================================================================
ERROR: seaborn.tests.test_linearmodels.TestRegressionPlotter.test_logistic_regression
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/travis/build/mwaskom/seaborn/seaborn/tests/test_linearmodels.py", line 347, in test_logistic_regression
    _, yhat, _ = p.fit_regression(x_range=(-3, 3))
  File "/home/travis/build/mwaskom/seaborn/seaborn/linearmodels.py", line 194, in fit_regression
    family=Binomial())
  File "/home/travis/build/mwaskom/seaborn/seaborn/linearmodels.py", line 250, in fit_statsmodels
    n_boot=self.n_boot, units=self.units)
  File "/home/travis/build/mwaskom/seaborn/seaborn/algorithms.py", line 76, in bootstrap
    boot_dist.append(func(*sample, **func_kwargs))
  File "/home/travis/build/mwaskom/seaborn/seaborn/linearmodels.py", line 244, in <lambda>
    reg_func = lambda _x, _y: model(_y, _x, **kwargs).fit().predict(grid)
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/statsmodels/genmod/generalized_linear_model.py", line 719, in fit
    raise PerfectSeparationError(msg)
statsmodels.tools.sm_exceptions.PerfectSeparationError: Perfect separation detected, results not available
```

**Comment by mwaskom** [comment]
Closed with #696 (probably)
