### ISSUE TITLE
2 Tests Fail: nested stats with missing data; single layer stats with missing data

### ISSUE THREAD

**Issue by jmwoloso** [mwaskom/seaborn#660]
Hello!

I was wondering if anyone had any insight into this output. I created a wheel from source (version 0.6.0) and installed. This was the result of the nosetests.

======================================================================
FAIL: seaborn.tests.test_categorical.TestCategoricalStatPlotter.test_nested_stats_with_missing_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/ap/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/source/packages/seaborn-0.6.0/seaborn/tests/test_categorical.py", line 591, in test_nested_stats_with_missing_data
    npt.assert_equal(p.statistic[1, 2], mean)
  File "/home/jason/.virtualenvs/ap/lib/python3.4/site-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0.018721526986487352
 DESIRED: -0.018721526986487342

======================================================================
FAIL: seaborn.tests.test_categorical.TestCategoricalStatPlotter.test_single_layer_stats_with_missing_data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/ap/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/source/packages/seaborn-0.6.0/seaborn/tests/test_categorical.py", line 516, in test_single_layer_stats_with_missing_data
    npt.assert_equal(p.statistic[1], mean)
  File "/home/jason/.virtualenvs/ap/lib/python3.4/site-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 0.082012970747837352
 DESIRED: 0.08201297074783731

----------------------------------------------------------------------
Ran 369 tests in 107.328s

FAILED (SKIP=5, failures=2)

**Comment by mwaskom** [comment]
Looks like floating point noise. Those should probably be `assert_almost_equal` but dunno why the failure doesn't happen on Travis.

**Comment by jmwoloso** [comment]
Ok, thanks for the prompt feedback! It might have to do with the compiler optimizations I used when building NumPy and SciPy. The difference isn't that much so I'll just disregard for the time being.
