### ISSUE TITLE
Error in tsplot

### ISSUE THREAD

**Issue by tboquet** [mwaskom/seaborn#662]
Hello all,

I had an error while trying to plot time series with `tsplot`.
This is the shape of my `pd.DataFrame`:
(1000, 3)
This is the shape of the 2 arrays I want to plot.
(1000,) (1000,)
This is the error I get when using:
```python
sns.tsplot(data=df.users, condition=df.shop)
```
```python
Traceback (most recent call last):
  File "DNU_hour_V2.py", line 80, in <module>
    sns.tsplot(data=np.array(df.users), condition=np.array(df.shop))
  File "/home/thomas/anaconda3/lib/python3.4/site-packages/seaborn/timeseries.py", line 248, in tsplot
    cond=conds))
  File "/home/thomas/anaconda3/lib/python3.4/site-packages/pandas/core/frame.py", line 214, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/thomas/anaconda3/lib/python3.4/site-packages/pandas/core/frame.py", line 341, in _init_dict
    dtype=dtype)
  File "/home/thomas/anaconda3/lib/python3.4/site-packages/pandas/core/frame.py", line 4798, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/thomas/anaconda3/lib/python3.4/site-packages/pandas/core/frame.py", line 4846, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length
```
Not sure what's going on there :)!

**Comment by mwaskom** [comment]
If you want to use a dataframe you have to identify the time, units, and value variables.

**Comment by tboquet** [comment]
Thank you @mwaskom, it's working! Because I have only one observation for each value, I had to put an array of 1 for the unit. I think it could be interesting to add an example in the documentation :).  I seem to have a well known problem about the legend (it's missing), I will check the other issues and post my config and problem there.

**Comment by mwaskom** [comment]
If you don't have multiple units, I don't think you want to be using seaborn's `tsplot`.
