### ISSUE TITLE
isinstance(x, str) breaks when using unicode_literals

### ISSUE THREAD

**Issue by richardsheridan** [mwaskom/seaborn#673]
I got bit pretty hard while trying to use cmap='Blues_d' in seaborn.kdeplot. Eventually I discovered that the problem involved python2's str vs unicode types. I always "from __future__ import unicode_literals" when working in python 2, so the cmap string was being passed through as though it were an object from blend_palette(). 

As a workaround, strings I send through seaborn are decorated with .encode('ascii'), but this bug should be fixed by using the six library or duck typing or something like that.

**Comment by mwaskom** [comment]
I don't really understand the problem. Can you provide some example code that breaks and a stack trace or something?

**Comment by richardsheridan** [comment]
It might be specific to two dimensional kdeplots where I ask for a cmap with the '_d' extension, as that is the only example I have on hand. Run on python 2.7 and uncomment the encode method to see expected behavior.

Example code:

    from __future__ import unicode_literals, division, print_function
    
    import seaborn as sb
    
    iris = sb.load_dataset('iris')
    p=sb.PairGrid(iris, diag_sharey=False, size=2)
    n=10
    cmap='Blues_d'#.encode('ascii')
    #cmap=None
    #colors = [(1.0,1.0,1.0)] + sb.color_palette('Blues',n-1)
    colors = None
    p.map_offdiag(sb.kdeplot, colors=colors, cmap=cmap, nlevels=n, shade=True)
    p.map_diag(sb.kdeplot, bw='silverman'.encode('ascii'), shade=True)

Stack Trace:

        
        Traceback (most recent call last):
      File "C:\Users\rjs3\Desktop\example.py", line 19, in <module>
        p.map_offdiag(sb.kdeplot, colors=colors, cmap=cmap, nlevels=n, shade=True)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\seaborn\axisgrid.py", line 1043, in map_offdiag
        self.map_lower(func, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\seaborn\axisgrid.py", line 987, in map_lower
        color=color, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\seaborn\distributions.py", line 862, in kdeplot
        cut, clip, legend, ax, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\seaborn\distributions.py", line 741, in _bivariate_kdeplot
        contour_func(xx, yy, z, n_levels, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\matplotlib\axes\_axes.py", line 5340, in contourf
        return mcontour.QuadContourSet(self, *args, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\matplotlib\contour.py", line 1429, in __init__
        ContourSet.__init__(self, ax, *args, **kwargs)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\matplotlib\contour.py", line 920, in __init__
        cm.ScalarMappable.__init__(self, **kw)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\matplotlib\cm.py", line 197, in __init__
        self.cmap = get_cmap(cmap)
      File "C:\Users\rjs3\Desktop\WinPython-32bit-2.7.9.5\python-2.7.9\lib\site-packages\matplotlib\cm.py", line 163, in get_cmap
        % (name, ', '.join(cmap_d.keys())))
    ValueError: Colormap Blues_d is not recognized. Possible values are: Spectral, summer, coolwarm, Wistia_r, pink_r, Set1, Set2, Set3, brg_r, Dark2, prism, PuOr_r, afmhot_r, terrain_r, PuBuGn_r, RdPu, gist_ncar_r, gist_yarg_r, Dark2_r, YlGnBu, RdYlBu, hot_r, gist_rainbow_r, gist_stern, PuBu_r, cool_r, cool, gray, copper_r, Greens_r, GnBu, gist_ncar, spring_r, gist_rainbow, gist_heat_r, Wistia, OrRd_r, CMRmap, bone, gist_stern_r, RdYlGn, Pastel2_r, spring, terrain, YlOrRd_r, Set2_r, winter_r, PuBu, RdGy_r, spectral, rainbow, flag_r, jet_r, RdPu_r, gist_yarg, BuGn, Paired_r, hsv_r, bwr, cubehelix, Greens, PRGn, gist_heat, spectral_r, Paired, hsv, Oranges_r, prism_r, Pastel2, Pastel1_r, Pastel1, gray_r, jet, Spectral_r, gnuplot2_r, gist_earth, YlGnBu_r, copper, gist_earth_r, Set3_r, OrRd, gnuplot_r, ocean_r, brg, gnuplot2, PuRd_r, bone_r, BuPu, Oranges, RdYlGn_r, PiYG, CMRmap_r, YlGn, binary_r, gist_gray_r, Accent, BuPu_r, gist_gray, flag, bwr_r, RdBu_r, BrBG, Reds, Set1_r, summer_r, GnBu_r, BrBG_r, Reds_r, RdGy, PuRd, Accent_r, Blues, autumn_r, autumn, cubehelix_r, nipy_spectral_r, ocean, PRGn_r, Greys_r, pink, binary, winter, gnuplot, RdYlBu_r, hot, YlOrBr, coolwarm_r, rainbow_r, Purples_r, PiYG_r, YlGn_r, Blues_r, YlOrBr_r, seismic, Purples, seismic_r, RdBu, Greys, BuGn_r, YlOrRd, PuOr, PuBuGn, nipy_spectral, afmhot

**Comment by mwaskom** [comment]
I don't get an error when I run the code you sent me verbatim. Am I supposed to change something to make the error happen?

**Comment by richardsheridan** [comment]
Looks like a version problem. Everything goes fine in 0.6.0. I was using
0.5.1, and in 0.6.0 the troublesome line has been changed to if
isinstance(cmap, six.string_types).

So.. bug fixed I guess.  Sorry!
