### ISSUE TITLE
ImportError: No module named '_gdbm'

### ISSUE THREAD

**Issue by j9ac9k** [mwaskom/seaborn#687]
This may not be an issue with seaborn, but an issue with spyre ( https://github.com/adamhajari/spyre ).  With starting a spyre web-application, if I import seaborn I get the following error:

```
ImportError: No module named '_gdbm'
```
I opened up an issue on the spyre repo here: https://github.com/adamhajari/spyre/issues/34

This is running on a Windows x64 platform, with Python 3.4.3, Seaborn 0.6, and Spyre 0.2.

To reproduce install spyre:

```
pip install dataspyre
```

Save the following contents into will_produce_error.py

```
from spyre import server
import seaborn as sns


class break_seaborn(server.App):
    title = "Testing Seaborn Incompatibility"

    inputs = [{ "type":"text",
                "label":'Text Field',
                "variable_name":"filename"}]

    controls = [{"control_type":"button",
                 "label":"Process",
                 "control_id":"process_data"}]


    outputs = [{"output_type":"plot",
                "output_id":"scatter_plot",
                "control_id": "process_data"}]



    def getPlot(self, params):
        variable = 'nothing here'

        return variable

app = break_seaborn()
app.launch(host='localhost')
```

From the command line run:

```
python will_produce_error.py
```

Any suggestions would be appreciated.

**Comment by mwaskom** [comment]
Can you just show me the full stack trace? I have no idea what that module is, but some context as to what's getting imported when the error gets raised might help..

**Comment by j9ac9k** [comment]
```
c:\Users\omoore\Documents\GitHub\web-image-processor>python seaborn_broke.py
Warning: unable to set defaultencoding to utf-8
[26/Aug/2015:13:56:57] ENGINE Listening for SIGTERM.
[26/Aug/2015:13:56:57] ENGINE Bus STARTING
[26/Aug/2015:13:56:57] ENGINE Set handler for console events.
CherryPy Checker:
The Application mounted at '' has an empty config.

[26/Aug/2015:13:56:57] ENGINE Started monitor thread '_TimeoutMonitor'.
[26/Aug/2015:13:56:57] ENGINE Started monitor thread 'Autoreloader'.
[26/Aug/2015:13:56:57] ENGINE Serving on http://0.0.0.0:8080
[26/Aug/2015:13:56:57] ENGINE Bus STARTED
[26/Aug/2015:13:56:58] ENGINE Error in background task thread function <bound me
thod Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x0000
00000638D9E8>>.
Traceback (most recent call last):
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\che
rrypy\process\plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\che
rrypy\process\plugins.py", line 632, in run
    for filename in self.sysfiles() | self.files:
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\che
rrypy\process\plugins.py", line 616, in sysfiles
    hasattr(m, '__loader__') and
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\sea
born\external\six.py", line 116, in __getattr__
    _module = self._resolve()
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\sea
born\external\six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\site-packages\sea
born\external\six.py", line 76, in _import_module
    __import__(name)
  File "C:\Users\omoore\AppData\Local\Continuum\Miniconda3\lib\dbm\gnu.py", line
 3, in <module>
    from _gdbm import *
ImportError: No module named '_gdbm'
```

Sorry about that, figured I was forgetting something.

**Comment by mwaskom** [comment]
Hm, kind of reminds me of https://github.com/mwaskom/seaborn/issues/475, another issue with six in a dynamic web app type context (which unfortunately I don't really know anything about...)

**Comment by j9ac9k** [comment]
Definitely looks similar for sure.  Anyway as stated earlier, I'm not convinced this is a seaborn issue; so feel free to close.

**Comment by mwaskom** [comment]
Well let's see if the Spyre folks have any ideas.

**Comment by j9ac9k** [comment]
Do you think it's worth opening an issue on the six bitbucket repo?

**Comment by mwaskom** [comment]
Probably would be most helpful to try and create a bare-bones example of the failure using a copy of the six module and cherrypy directly.

FWIW I don't see this error on my system, (OSX and Python 2) although I also don't seem to get a working app when I visit the port it claims it's serving on.

**Comment by j9ac9k** [comment]
Since you mentioned it working on OSX with Python 2, I fired up an ubuntu VM, with python 3, got the following error:

```
ogi@ubuntu:~/web-image-processor$ python seaborn_broke.py
Warning: unable to set defaultencoding to utf-8
[28/Aug/2015:12:09:55] ENGINE Listening for SIGTERM.
[28/Aug/2015:12:09:55] ENGINE Listening for SIGUSR1.
[28/Aug/2015:12:09:55] ENGINE Listening for SIGHUP.
[28/Aug/2015:12:09:55] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.

[28/Aug/2015:12:09:55] ENGINE Started monitor thread 'Autoreloader'.
[28/Aug/2015:12:09:55] ENGINE Started monitor thread '_TimeoutMonitor'.
[28/Aug/2015:12:09:56] ENGINE Serving on http://0.0.0.0:8080
[28/Aug/2015:12:09:56] ENGINE Bus STARTED
[28/Aug/2015:12:09:56] ENGINE Error in background task thread function <bound method Autoreloader.run of <cherrypy.process.plugins.Autoreloader object at 0x7efd5b5b29b0>>.
Traceback (most recent call last):
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 632, in run
    for filename in self.sysfiles() | self.files:
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 616, in sysfiles
    hasattr(m, '__loader__') and
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named 'winreg'

Exception in thread Autoreloader:
Traceback (most recent call last):
  File "/home/ogi/miniconda3/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 500, in run
    self.function(*self.args, **self.kwargs)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 632, in run
    for filename in self.sysfiles() | self.files:
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/cherrypy/process/plugins.py", line 616, in sysfiles
    hasattr(m, '__loader__') and
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/home/ogi/miniconda3/lib/python3.4/site-packages/seaborn/external/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named 'winreg'
```

However with I created a python 2 conda environment, it ran just fine.

Thanks for looking into it.  I'll see how I can go about trying to create a minimal examples with six and cherrypy modules.

**Comment by pybokeh** [comment]
I am getting the same error (on Windows 7) with Python 3.5.2.

I was able to get the example working by modifying the ```gnu.py``` file:

I changed:
```python
from _gdbm import *
```
to
```python
from dbm import *
```

**Comment by pybokeh** [comment]
With regards to Ubuntu and winreg import error, this [fix](https://github.com/cherrypy/cherrypy/issues/1341) worked for me.
