### ISSUE TITLE
pandas 0.17.0rc1

### ISSUE THREAD

**Issue by jreback** [mwaskom/seaborn#702]
we have some fairly significant changes and would like you to test and provide any feedback: https://github.com/pydata/pandas/releases/tag/v0.17.0rc1

thanks!

**Comment by mwaskom** [comment]
Thanks for the heads up. Some failures I need to sort out.

Any idea why the warning about the `sort` API deprecation is getting raised from a weird place?

```
../Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
```

**Comment by mwaskom** [comment]
For posterity 

```
(pandas_dev)[mwmp seaborn]{master}$ make test
cp testing/matplotlibrc .
nosetests --with-doctest
/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/indexing.py:115: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
/Users/mwaskom/code/seaborn/seaborn/axisgrid.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
F/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/matplotlib/pyplot.py:424: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
../Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
.../Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
./Users/mwaskom/code/seaborn/seaborn/categorical.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from __future__ import division
........./Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/matplotlib/colorbar.py:215: UserWarning: Use the colorbar set_ticks() method instead.
  warnings.warn("Use the colorbar set_ticks() method instead.")
..........................................S.........................................................................................................................................................................................................................................SS..........................................................................................................SSS
======================================================================
FAIL: Doctest: seaborn.axisgrid.FacetGrid.__init__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for seaborn.axisgrid.FacetGrid.__init__
  File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 389, in __init__

----------------------------------------------------------------------
File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 605, in seaborn.axisgrid.FacetGrid.__init__
Failed example:
    df = pd.DataFrame(
        data=np.random.randn(90, 4),
        columns=pd.Series(list("ABCD"), name="walk"),
        index=pd.date_range("Jan 1", "March 31", name="date"))
Exception raised:
    Traceback (most recent call last):
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.axisgrid.FacetGrid.__init__[34]>", line 4, in <module>
        index=pd.date_range("Jan 1", "March 31", name="date"))
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tseries/index.py", line 1913, in date_range
        closed=closed)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/util/decorators.py", line 89, in wrapper
        return func(*args, **kwargs)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tseries/index.py", line 236, in __new__
        ambiguous=ambiguous)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tseries/index.py", line 385, in _generate
        start = Timestamp(start)
      File "pandas/tslib.pyx", line 298, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:8496)
      File "pandas/tslib.pyx", line 1146, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:21832)
      File "pandas/tslib.pyx", line 1277, in pandas.tslib.convert_str_to_tsobject (pandas/tslib.c:23893)
      File "pandas/tslib.pyx", line 1211, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:22873)
      File "pandas/tslib.pyx", line 1415, in pandas.tslib._check_dts_bounds (pandas/tslib.c:26119)
    OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-01-01 00:00:00
----------------------------------------------------------------------
File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 609, in seaborn.axisgrid.FacetGrid.__init__
Failed example:
    df = df.cumsum(axis=0).stack().reset_index(name="val")
Exception raised:
    Traceback (most recent call last):
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.axisgrid.FacetGrid.__init__[35]>", line 1, in <module>
        df = df.cumsum(axis=0).stack().reset_index(name="val")
    NameError: name 'df' is not defined
----------------------------------------------------------------------
File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 614, in seaborn.axisgrid.FacetGrid.__init__
Failed example:
    g = sns.FacetGrid(df, col="walk", col_wrap=2, size=3.5)
Exception raised:
    Traceback (most recent call last):
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.axisgrid.FacetGrid.__init__[37]>", line 1, in <module>
        g = sns.FacetGrid(df, col="walk", col_wrap=2, size=3.5)
    NameError: name 'df' is not defined
----------------------------------------------------------------------
File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 615, in seaborn.axisgrid.FacetGrid.__init__
Failed example:
    g = g.map_dataframe(dateplot, "date", "val")
Exception raised:
    Traceback (most recent call last):
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest seaborn.axisgrid.FacetGrid.__init__[38]>", line 1, in <module>
        g = g.map_dataframe(dateplot, "date", "val")
      File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 792, in map_dataframe
        self._facet_plot(func, ax, args, kwargs)
      File "/Users/mwaskom/code/seaborn/seaborn/axisgrid.py", line 810, in _facet_plot
        func(*plot_args, **plot_kwargs)
      File "<doctest seaborn.axisgrid.FacetGrid.__init__[36]>", line 4, in dateplot
        data.plot(x=x, y=y, ax=ax, grid=False, **kwargs)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tools/plotting.py", line 3610, in __call__
        sort_columns=sort_columns, **kwds)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tools/plotting.py", line 2495, in plot_frame
        **kwds)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/tools/plotting.py", line 2303, in _plot
        data = data.set_index(x)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/frame.py", line 2726, in set_index
        level = frame[col]._values
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/frame.py", line 1915, in __getitem__
        return self._getitem_column(key)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/frame.py", line 1922, in _getitem_column
        return self._get_item_cache(key)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/generic.py", line 1090, in _get_item_cache
        values = self._data.get(item)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/internals.py", line 3052, in get
        loc = self.items.get_loc(item)
      File "/Users/mwaskom/anaconda/envs/pandas_dev/lib/python2.7/site-packages/pandas/core/index.py", line 1685, in get_loc
        return self._engine.get_loc(_values_from_object(key))
      File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
      File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
      File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
      File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
    KeyError: 'date'


----------------------------------------------------------------------
Ran 405 tests in 160.745s

FAILED (SKIP=6, failures=1)
make: *** [test] Error 1
```

**Comment by jreback** [comment]
@mwaskom yep, we were afraid of the downstream deprecation showing (so maybe we will make it a ``DeprecationWarning`` rather than a ``FutureWarning``

**Comment by jreback** [comment]
``pd.date_range("Jan 1", "March 31", name="date")`` was 'accidently working', see [here](http://pandas-docs.github.io/pandas-docs-travis/whatsnew.html#other-enhancements) down a little ways and is not valid. replace by actual dates.

**Comment by jreback** [comment]
any remaining issues with the rc1?

**Comment by mwaskom** [comment]
Sorry I've had 0 bandwidth for seaborn recently. IIRC, the only issues were with how I was invoking pandas in the doctests, so I don't think you should consider anything a blocker from my side
