### ISSUE TITLE
Use of dictionary for pointplot palette fails

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#717]
The use of a dictionary for a [`pointplot`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.pointplot.html) palette fails.

For a dictionary of the form: {'a': 'hls', 'b': 'Set3', 'c': 'Accent', 'd': 'Dark2', 'e': 'Set1'}, supplied to the `palette` parameter, the following error is returned:

`Traceback (most recent call last):
  File "./createFacetedLinePlots.py", line 409, in <module>
    palette=colour_pal, markers=markers)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 726, in map
    self._facet_plot(func, ax, plot_args, kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 810, in _facet_plot
    func(*plot_args, **plot_kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/categorical.py", line 2353, in pointplot
    orient, color, palette)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/categorical.py", line 1317, in __init__
    self.establish_colors(color, palette, 1)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/categorical.py", line 289, in establish_colors
    colors = color_palette(palette, n_colors)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/palettes.py", line 191, in color_palette
    raise ValueError("Could not generate a palette for %s" % str(palette))
ValueError: Could not generate a palette for ['Set1', 'Accent', 'Dark2']`

However, this dictionary looks like it should work, based upon the [relevant `axisgrid.py` code](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L155), since it simply delegates to [`color_palette`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.color_palette.html).

**Comment by mwaskom** [comment]
The values should be colors, not color palette names.

**Comment by cviner** [comment]
I guess that does make sense given that it is assigned to a specific hue value. Thanks.
