### ISSUE TITLE
Use of hue_order with faceted pointplot

### ISSUE THREAD

**Issue by cviner** [mwaskom/seaborn#718]
I am having difficulty using `hue_order` with a [`pointplot`](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.pointplot.html) mapped onto a [`FacetGrid`](stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html).

Specifically, it is difficult to construct a `hue_order` to pass in the `pointplot` call (it can't go in the `FacetGrid` call since I am specifying the hue at the level of `pointplot`) since the `pointplot` is being mapped onto the `FacetGrid` and an error results when a `hue_order` is provided which states the order for all categories across all facets.

Interestingly, the error is similar to the error encountered with `factorplot` (reported in issue #709):

```
Traceback (most recent call last):
  File "./createFacetedLinePlots.py", line 452, in <module>
    labelspacing=0.)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 92, in add_legend
    plt.draw()
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 571, in draw
    get_current_fig_manager().canvas.draw()
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/collections.py", line 772, in draw
    Collection.draw(self, renderer)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/collections.py", line 259, in draw
    self.update_scalarmappable()
  File "/mnt/work1/users/home2/cviner/.local/lib/python2.7/site-packages/matplotlib/collections.py", line 672, in update_scalarmappable
    raise ValueError('Collections can only map rank 1 arrays')
ValueError: Collections can only map rank 1 arrays
```

**Comment by cviner** [comment]
The above error additionally occurs when `hue_order` is not specified, but `DataFrame` columns are converted to the [`category` dtype](http://pandas-docs.github.io/pandas-docs-travis/categorical.html). Perhaps this (and possibly issue #709) are due to some issue with that data type?

**Comment by mwaskom** [comment]
This is the same issue as #709 right?

**Comment by cviner** [comment]
It looks like it is, in that the traceback is identical once down far enough and both appear to have `hue_order` as a root cause. However the issues are distinct in the sense that issue #709 uses `factorplot`, while this issue directly uses `FacetGrid` and `pointplot`.

**Comment by mwaskom** [comment]
Right, but `factorplot` is just a thin wrapper around `FacetGrid` and `pointplot`...

**Comment by cviner** [comment]
Well, yes. I just wasn't certain that these had the exact same cause, but might instead be two means of obtaining the same error, especially given that this was observed with the `category` data type as well, without any `hue_order`. Considering these the same bug does make sense, in hindsight.

**Comment by cviner** [comment]
@mwaskom: Can you think of any work-around for this such that the list of `markers` I provide to `pointplot` corresponds to the order in which they appear in the legend (as discussed in pull request #714)?

**Comment by cviner** [comment]
I can't really discern what order the markers provided are being applied to WRT the hues. I can see that `pointplot` uses the following on [line 207 of `categorical.py`](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L207):

    hue_names = categorical_order(hue, hue_order)

and I have looked at [`categorical_order` in `utils.py`](https://github.com/mwaskom/seaborn/blob/master/seaborn/utils.py#L493). If I am interpreting the code correctly, since my `hue` is not a categorical datatype (since that also results in the above error), and it is not of type `np.float`, then the order is simply the result of calling `unique()` on the `hue` column. However, this does not appear to be the case. Does some kind of internal reordering occur that I am not aware of?

**Comment by mwaskom** [comment]
It might be best to try to replicate the behavior that you are seeing with one of the example datasets so that I can more easily debug it. I think the answer to your last question is that the ordering by `unique` might be different for each subset of the dataframe corresponding to each facet, so the default hue order will be different (hence the need to specify hue order, as factorplot does).

**Comment by cviner** [comment]
Thanks, @mwaskom.

**Comment by mwaskom** [comment]
Also it might be useful to use `barplot` to understand what's happening. The internals are identical to `pointplot`, it's just drawn differently, so it might help.
