### ISSUE TITLE
Distplot Edge Case Bug

### ISSUE THREAD

**Issue by seewalker** [mwaskom/seaborn#765]
I'm using seaborn version 0.6.0 and python version 3.4.3.

When I try to produce a distplot when all the values are the same, I get a `numpy.linalg.linalg.LinAlgError: singular matrix` error. Rather than bailing upon a uniform distribution, seaborn should probably handle that case in a conditional rather than continuing with the computations that produce a singular matrix error. The full backtrace I get is:

```
Traceback (most recent call last):
  File "sketch.py", line 79, in independent_w_normal
    sns.distplot(list(actual_frequencies.values()),color=pcolors[j], ax=axis)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/seaborn/distributions.py", line 218, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/seaborn/distributions.py", line 601, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/seaborn/distributions.py", line 278, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/seaborn/distributions.py", line 336, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/scipy/stats/kde.py", line 171, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/scipy/stats/kde.py", line 488, in set_bandwidth
    self._compute_covariance()
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/scipy/stats/kde.py", line 499, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/Users/shalom/anaconda/envs/py3k/lib/python3.4/site-packages/scipy/linalg/basic.py", line 677, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
```

**Comment by seewalker** [comment]
To clarify what I meant by 'uniform distribution', `list(actual_frequencies.values())` in this case is something like `[10,10,10,10]`.

**Comment by mwaskom** [comment]
Looks like this should be directed towards scipy?

**Comment by seewalker** [comment]
I'm not sure, should it? There are a few layers that the error could be caught at, and catching it at the application layer seems like the only obviously bad idea to me (which is why i raised an issue). Maybe there is a good rationale for this being either scipy or seaborn's responsibility?

**Comment by vadimkantorov** [comment]
Same issue in `0.8.1` (python 2.7.12), kernel density estimation fails when data are very close.

I expected the plotting should recover from this kind of error, at least in the default mode.
