### ISSUE TITLE
test failures with version 0.7.0

### ISSUE THREAD

**Issue by jlec** [mwaskom/seaborn#836]
```python
======================================================================
FAIL: seaborn.tests.test_matrix.TestDendrogram.test_dendrogram_ticklabel_rotation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/seaborn-0.7.0/work/seaborn-0.7.0/seaborn/tests/test_matrix.py", line 587, in test_dendrogram_ticklabel_rotation
    nt.assert_equal(t.get_rotation(), 90)
AssertionError: 0.0 != 90

======================================================================
FAIL: seaborn.tests.test_matrix.TestHeatmap.test_heatmap_ticklabel_rotation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/seaborn-0.7.0/work/seaborn-0.7.0/seaborn/tests/test_matrix.py", line 309, in test_heatmap_ticklabel_rotation
    nt.assert_equal(t.get_rotation(), 90)
AssertionError: 0.0 != 90

----------------------------------------------------------------------
```
scipy-0.16.1
numpy-1.10.4
python-3.4/2.7

**Comment by mwaskom** [comment]
What matplotlib backend?

**Comment by mwaskom** [comment]
And what version of matplotlib for that matter.

**Comment by jlec** [comment]
> What matplotlib backend?

Didn't set any special, so I assume it's agg.

> And what version of matplotlib for that matter.

Version 1.5.1

**Comment by jlec** [comment]
Okay, I did set the backend now to agg and it works.

**Comment by mwaskom** [comment]
There is a bug in some of the other backends that prevents the label overlap detection and hence label rotation. From my perspective the Agg results are the gold standard, because it is the most stable, and it is available everywhere.
