### ISSUE TITLE
Failed to install seaborn on smartos(solaris like system) 

### ISSUE THREAD

**Issue by FrankYu** [mwaskom/seaborn#948]
#pip install seaborn 
Collecting seaborn
  Using cached seaborn-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0zj1ya/seaborn/setup.py", line 66, in <module>
        install_requires = check_dependencies()
      File "/tmp/pip-build-0zj1ya/seaborn/setup.py", line 58, in check_dependencies
        import pandas
      File "/opt/local/lib/python2.7/site-packages/pandas/__init__.py", line 25, in <module>
        from pandas import hashtable, tslib, lib
      File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38364)
    ValueError: numpy.dtype has the wrong size, try recompiling. Expected 88, got 96
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0zj1ya/seaborn/

and below is what I have installed:

#pip list 
chicken (0.1.0)
egg (0.2.0)
hmmlearn (0.2.0)
matplotlib (1.3.1)
nose (1.3.7)
numpy (1.9.2)
pandas (0.18.1)
patsy (0.4.1)
pip (8.1.2)
pykalman (0.9.5)
pymc (2.3.6)
pyparsing (2.1.0)
python-dateutil (2.4.0)
pytz (2016.4)
scikit-learn (0.17.1)
scipy (0.17.1)
setuptools (20.2.2)
six (1.10.0)
sklearn (0.0)
statsmodels (0.6.1)
TA-Lib (0.4.9)

**Comment by mwaskom** [comment]
Looks like a problem compiling either numpy or pandas, which are imported by seaborn.
