### ISSUE TITLE
sns.violinplot() fails in draw_box_lines() with [0.9999997000000901, 0.99999970000009].

### ISSUE THREAD

**Issue by jfreidin** [mwaskom/seaborn#949]
```
$ python -i
Python 2.7.11 (default, May 23 2016, 07:13:45) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('Agg')
>>> import matplotlib.pyplot as plt
>>> import seaborn as sns
>>> data = [[0.9999997000000901, 0.99999970000009]]
>>> plt.violinplot(data, showmeans=True, showextrema=True, showmedians=True)
{u'cbars': <matplotlib.collections.LineCollection object at 0x7f034759d690>, u'cmedians': <matplotlib.collections.LineCollection object at 0x7f034759dbd0>, u'cmins': <matplotlib.collections.LineCollection object at 0x7f034759d150>, u'cmaxes': <matplotlib.collections.LineCollection object at 0x7f0347583bd0>, u'bodies': [<matplotlib.collections.PolyCollection object at 0x7f0347583310>], u'cmeans': <matplotlib.collections.LineCollection object at 0x7f03475831d0>}
>>> sns.violinplot(data=data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python2.7/site-packages/seaborn/categorical.py", line 2352, in violinplot
    plotter.plot(ax)
  File "lib/python2.7/site-packages/seaborn/categorical.py", line 1062, in plot
    self.draw_violins(ax)
  File "lib/python2.7/site-packages/seaborn/categorical.py", line 820, in draw_violins
    self.draw_box_lines(ax, violin_data, support, density, i)
  File "lib/python2.7/site-packages/seaborn/categorical.py", line 975, in draw_box_lines
    h1 = np.min(data[data >= (q25 - whisker_lim)])
  File "lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2359, in amin
    out=out, keepdims=keepdims)
  File "lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
>>> 
```

matplotlib (1.5.1)
numpy (1.11.0)
seaborn (0.7.1)

**Comment by mwaskom** [comment]
I get a similar output as with `plt.violinplot` if I do `sns.violinplot(data=data, inner=None)`.
