### ISSUE TITLE
Incompatibility with scipy 0.18.0

### ISSUE THREAD

**Issue by meklon** [mwaskom/seaborn#998]
I use your library in my project [DAB_analyzer](https://github.com/meklon/DAB_analyzer). I've noticed troubles after upgrading scipy from 0.17.0 to 0.18.0.
Here is the console output:
```
meklon@RegenLab-LinuxDesktop-1:/mnt/Data/ownCloud/RegenLab/Software/PyCharm projects/DAB_analyzer/test images$ dabanalyzer -p sample\ example/ -s -a
Output result directory already exists. All the files inside would be overwritten!
Images for analysis: 5
DAB threshold = 40, Empty threshold = 101
Empty area filtering is disabled.
It should be adjusted in a case of hollow organ or unavoidable edge defects
CPU cores used: 2
Image saved: sample example/result/Alex_Pan_06_analysis.png
Image saved: sample example/result/Alex_Pan_08_analysis.png
Image saved: sample example/result/Native_Pan_04_analysis.png
Image saved: sample example/result/Native_Pan_05_analysis.png
Image saved: sample example/result/Native_Trop_02_analysis.png
CSV saved: sample example/result/analysis.csv
Group analysis is active
/usr/local/lib/python3.5/dist-packages/dabanalyzer/dab_deconv_area.py:345: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  df = df.convert_objects(convert_numeric=True)
          mean       std  median   amin   amax
Group                                         
Alex    49.165  2.170818  49.165  47.63  50.70
Native  12.840  8.031046   9.320   7.17  22.03
Traceback (most recent call last):
  File "/usr/local/bin/dabanalyzer", line 9, in <module>
    load_entry_point('dabanalyzer==1.6', 'console_scripts', 'dabanalyzer')()
  File "/usr/local/lib/python3.5/dist-packages/dabanalyzer/dab_deconv_area.py", line 442, in main
    group_analyze(filenames, arrayData, pathOutput)
  File "/usr/local/lib/python3.5/dist-packages/dabanalyzer/dab_deconv_area.py", line 350, in group_analyze
    plot_group(df, path_output)
  File "/usr/local/lib/python3.5/dist-packages/dabanalyzer/dab_deconv_area.py", line 355, in plot_group
    import seaborn as sns
  File "/usr/local/lib/python3.5/dist-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/usr/local/lib/python3.5/dist-packages/seaborn/rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "/usr/local/lib/python3.5/dist-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/usr/local/lib/python3.5/dist-packages/seaborn/utils.py", line 8, in <module>
    from scipy import stats
  File "/usr/lib/python3/dist-packages/scipy/stats/__init__.py", line 338, in <module>
    from .stats import *
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 183, in <module>
    from . import distributions
  File "/usr/lib/python3/dist-packages/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/usr/lib/python3/dist-packages/scipy/optimize/__init__.py", line 233, in <module>
    from ._minimize import *
  File "/usr/lib/python3/dist-packages/scipy/optimize/_minimize.py", line 30, in <module>
    from .lbfgsb import _minimize_lbfgsb
  File "/usr/lib/python3/dist-packages/scipy/optimize/lbfgsb.py", line 44, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/usr/lib/python3/dist-packages/scipy/sparse/linalg/__init__.py", line 112, in <module>
    from .isolve import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/linalg/isolve/iterative.py", line 10, in <module>
    from scipy._lib.decorator import decorator
ImportError: No module named 'scipy._lib.decorator'
```

**Comment by mmagnuski** [comment]
Seaborn only does `from scipy import stats` there. Take a look [here] (https://github.com/scipy/scipy/issues/5240) - it may be a mixup of two scipy installs. Try creating an environment with conda that has relevant dependencies and see if the problem persists.

**Comment by meklon** [comment]
Yes, looks like it's my local problem. Tested on the separate PC with clean install of scipy. It works.
